### ISSUE TITLE
CreateKaaeIndex - Cannot read property 'indices' of undefined

### ISSUE THREAD

**Issue by gubr123** [sirensolutions/sentinl#109]
Hi
Using kibana ,ES and searchguard v5.2.1

kaae v5.0.2

installed the kaae, changed the version in the package.json to 5.2.1

the error im getting when starting the kibana is:

> FATAL TypeError: Cannot read property 'indices' of undefined
    at Object.createKaaeIndex (/usr/share/kibana/plugins/kaae/server/lib/helpers.js:51:15)
    at ScopedPlugin.module.exports [as externalInit] (/usr/share/kibana/plugins/kaae/init.js:20:15)
    at ScopedPlugin.tryCatcher (/usr/share/kibana/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.attempt.Promise.try (/usr/share/kibana/node_modules/bluebird/js/main/method.js:30:24)
    at /usr/share/kibana/src/server/plugins/plugin.js:160:44
    at undefined.next (native)
    at step (/usr/share/kibana/src/server/plugins/plugin.js:11:273)

Any ideas?

**Comment by felixrod78** [comment]
Same issue here
TypeError: Cannot read property 'indices' of undefined
    at Object.createKaaeIndex (/kibana-5.2.2-linux-x86_64/plugins/kaae/server/lib/helpers.js:51:15)
    at ScopedPlugin.module.exports [as externalInit] (/kibana-5.2.2-linux-x86_64/plugins/kaae/init.js:20:15)
    at ScopedPlugin.tryCatcher (/kibana-5.2.2-linux-x86_64/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.attempt.Promise.try (/kibana-5.2.2-linux-x86_64/node_modules/bluebird/js/main/method.js:30:24)
    at /kibana-5.2.2-linux-x86_64/src/server/plugins/plugin.js:160:44
    at undefined.next (native)
    at step (/kibana-5.2.2-linux-x86_64/src/server/plugins/plugin.js:11:273)

**Comment by lmangani** [comment]
Apologies fellas, 5.x support is a high priority but still in the pipeline for the coming weeks, to port all the Sentinl code into the Kaae 5.x branch which right now sits behind it.

This being said your reports are key to speeding up the process, so keep them coming!

**Comment by felixrod78** [comment]
Hi
We are also not able to install sentinell on kibana 5.2.2

Any requisite?

2017-03-02 12:33 GMT+01:00 Lorenzo Mangani <notifications@github.com>:

**Comment by lmangani** [comment]
Sentinl is still being ported to 5.x and shall be available in the coming weeks alongside Kibi 5.x
