### ISSUE TITLE
Searchguard Kibana Plugin, Kibana5 and Sentinl

### ISSUE THREAD

**Issue by djtecha** [sirensolutions/sentinl#110]
Trying to install to the latest kibana 5.2.1 and it refused to startup after setting the package.json file and bouncing.

```
{"type":"log","@timestamp":"2017-03-09T00:19:59Z","tags":["fatal"],"pid":11297,"level":"fatal","message":"Cannot read property 'indices' of undefined","error":{"message":"Cannot read property 'indices' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'indices' of undefined\n    at Object.createKaaeIndex (/usr/share/kibana/plugins/kaae/server/lib/helpers.js:51:15)\n    at ScopedPlugin.module.exports [as externalInit] (/usr/share/kibana/plugins/kaae/init.js:20:15)\n    at ScopedPlugin.tryCatcher (/usr/share/kibana/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise.attempt.Promise.try (/usr/share/kibana/node_modules/bluebird/js/main/method.js:30:24)\n    at /usr/share/kibana/src/server/plugins/plugin.js:160:44\n    at undefined.next (native)\n    at step (/usr/share/kibana/src/server/plugins/plugin.js:11:273)\n    at process._tickCallback (internal/process/next_tick.js:103:7)"}}
```
This might be caused by me using the Searhguard plugin but I'm not entirely sure. Is there a way to pass the auth credentials with this plugin or does it just inherit the elasticsearch.username credentials?

**Comment by lmangani** [comment]
Current code is dev-only, really. A new release for 5.x is in the making and should see the light soon. Keep watching the repository.
