### ISSUE TITLE
sentinl run-time error

### ISSUE THREAD

**Issue by andryzhu** [sirensolutions/sentinl#127]
Hi,
I installed sentinl 5.2.2 on Kibana 5.3.0 successfully.
Then, when I start Kibana, I see the following log every 2m :

May 26 16:27:56 elk2 kibana: Unhandled rejection TypeError: _lodash2.default.contains is not a function
May 26 16:27:56 elk2 kibana: at handleESError (/apps/elk/kibana-5.3.0/plugins/sentinl/server/lib/handle_es_error.js:34:54)
May 26 16:27:56 elk2 kibana: at /apps/elk/kibana-5.3.0/plugins/sentinl/server/routes/routes.js:48:25
May 26 16:27:56 elk2 kibana: at bound (domain.js:280:14)
May 26 16:27:56 elk2 kibana: at runBound (domain.js:293:12)
May 26 16:27:56 elk2 kibana: at tryCatcher (/apps/elk/kibana-5.3.0/node_modules/bluebird/js/main/util.js:26:23)
May 26 16:27:56 elk2 kibana: at Promise._settlePromiseFromHandler (/apps/elk/kibana-5.3.0/node_modules/bluebird/js/main/promise.js:503:31)
May 26 16:27:56 elk2 kibana: at Promise._settlePromiseAt (/apps/elk/kibana-5.3.0/node_modules/bluebird/js/main/promise.js:577:18)
May 26 16:27:56 elk2 kibana: at Promise._settlePromises (/apps/elk/kibana-5.3.0/node_modules/bluebird/js/main/promise.js:693:14)
May 26 16:27:56 elk2 kibana: at Async._drainQueue (/apps/elk/kibana-5.3.0/node_modules/bluebird/js/main/async.js:123:16)
May 26 16:27:56 elk2 kibana: at Async._drainQueues (/apps/elk/kibana-5.3.0/node_modules/bluebird/js/main/async.js:133:10)
May 26 16:27:56 elk2 kibana: at Immediate.Async.drainQueues (/apps/elk/kibana-5.3.0/node_modules/bluebird/js/main/async.js:15:14)
May 26 16:27:56 elk2 kibana: at runCallback (timers.js:649:20)
May 26 16:27:56 elk2 kibana: at tryOnImmediate (timers.js:622:5)
May 26 16:27:56 elk2 kibana: at processImmediate [as _immediateCallback] (timers.js:594:5)

Created watchers, which is also doesn't work
My environment :
       OS: CentOS 7 kernel   3.10.0-514.10.2.el7.x86_64
       Elastic 5.30 + kibana 5.3.0

**Comment by lmangani** [comment]
Thanks for the report - Kibana 5.2.x != 5.3.x so this is sort of expected behaviour.
A release for 5.3 should come up as soon as we stabilized 5.2.2

**Comment by andryzhu** [comment]
I've tried kibana 5.2.2 ,when i click the "Alarms" or "reports", I also see the following error log:
Unhandled rejection TypeError: _lodash2.default.contains is not a function
    at handleESError (/apps/elk/kibana-5.2.2-linux-x86_64/plugins/sentinl/server/lib/handle_es_error.js:34:54)
    at /apps/elk/kibana-5.2.2-linux-x86_64/plugins/sentinl/server/routes/routes.js:48:25
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/apps/elk/kibana-5.2.2-linux-x86_64/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/apps/elk/kibana-5.2.2-linux-x86_64/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/apps/elk/kibana-5.2.2-linux-x86_64/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/apps/elk/kibana-5.2.2-linux-x86_64/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/apps/elk/kibana-5.2.2-linux-x86_64/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/apps/elk/kibana-5.2.2-linux-x86_64/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/apps/elk/kibana-5.2.2-linux-x86_64/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

Created watchers, which is also doesn't work

**Comment by SergeyBondarenko** [comment]
@andryzhu please try the latest release https://github.com/sirensolutions/sentinl/releases/tag/tag-5.3.2

**Comment by SergeyBondarenko** [comment]
@andryzhu If you need exactly 5.2.2 version, please try the 5.2.2-1 release https://github.com/sirensolutions/sentinl/releases/tag/tag-5.2.2-1. Feel free to re-open this issue if you still have problems.
