### ISSUE TITLE
Using it with Multi User Kibana

### ISSUE THREAD

**Issue by shubhamverma27** [sirensolutions/sentinl#145]
Hi,
I have Been trying to use it with a multi user kibana and have found the problem.
Problem is that it works when I login as the user whose userid and password is same as the elasticsearch authentication
but doesn't if its someone else.
I am using ReadonlyRest plugin for authentication.
Even a user with admin access to Kibana is not able to use it as its not being authenticated to elasticsearch.
Requesting the developer to add a option in .yml file to mention elastic search username and password!!!

**Comment by shubhamverma27** [comment]
Even in this setting , the watcher is saving but getting  No indices found error in logs.. ie its not able to read

**Comment by lmangani** [comment]
@shubhamverma27 please attach the error logs so we can work this out more efficiently. Sentinl uses the Kibana authentication details indeed, but can easily be extended in other directions, too.

**Comment by shubhamverma27** [comment]
log   [10:37:37.916] [info][status][Sentinl] Get scripts with type: transform
  log   [10:37:38.003] [info][status][Sentinl] Get scripts with type: input
  log   [10:37:38.046] [info][status][Sentinl] Get scripts with type: condition
  log   [10:37:55.232] [info][status][Sentinl] No indices found, Initializing
  log   [10:37:57.855] [info][status][Sentinl] Saving scripts with type: condition
  log   [10:38:25.231] [info][status][Sentinl] No indices found, Initializing
  log   [10:38:55.233] [info][status][Sentinl] No indices found, Initializing
got an error [404] Not Found
  log   [10:39:15.446] [warning][process] TypeError: this._next is not a function
    at Function.internals.continue (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/reply.js:108:10)
    at server.ext (/home/test/elk/kibana-5.4.1-linux-x86_64/plugins/readonlyrest_kbn/server/routes/lib/auth.js:6:2315)
    at Items.serial (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:403:22)
    at iterate (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at Function.wrapped [as _next] (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
    at Function.internals.continue (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/reply.js:108:10)
    at /home/test/elk/kibana-5.4.1-linux-x86_64/src/server/http/index.js:121:28
    at Items.serial (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:403:22)
    at iterate (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:39:9)
    at _protect.run (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:398:15)
    at internals.Protect.run (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/protect.js:64:5)
    at internals.Request._invoke (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:396:19)
    at internals.Request._reply (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:455:10)
    at Items.serial (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:389:21)
    at done (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:31:25)
    at finalize (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/handler.js:21:16)
    at Hoek.once (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/protect.js:52:16)
    at wrapped (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
    at finalize (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/handler.js:82:20)
    at Function.wrapped [as _next] (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
  log   [10:39:15.531] [info][status][Sentinl] Get scripts with type: transform
  log   [10:39:15.538] [info][status][Sentinl] Get scripts with type: input
  log   [10:39:15.540] [info][status][Sentinl] Get scripts with type: condition
  log   [10:39:25.234] [info][status][Sentinl] No indices found, Initializing
  log   [10:39:55.238] [info][status][Sentinl] No indices found, Initializing
  log   [10:40:14.029] [info][status][Sentinl] Saving scripts with type: input
  log   [10:40:25.240] [info][status][Sentinl] No indices found, Initializing
  log   [10:40:33.410] [info][status][Sentinl] Saving scripts with type: condition
  log   [10:40:55.243] [info][status][Sentinl] No indices found, Initializing
  log   [10:41:08.347] [info][status][Sentinl] Delete script with type/id: transform/null
got an error [404] Not Found
Unhandled rejection TypeError: this._next is not a function
    at Function.internals.continue (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/reply.js:108:10)
    at server.ext (/home/test/elk/kibana-5.4.1-linux-x86_64/plugins/readonlyrest_kbn/server/routes/lib/auth.js:6:2315)
    at Items.serial (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:403:22)
    at iterate (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at Function.wrapped [as _next] (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
    at Function.internals.continue (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/reply.js:108:10)
    at /home/test/elk/kibana-5.4.1-linux-x86_64/src/server/http/index.js:121:28
    at Items.serial (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:403:22)
    at iterate (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:39:9)
    at _protect.run (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:398:15)
    at internals.Protect.run (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/protect.js:64:5)
    at internals.Request._invoke (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:396:19)
    at internals.Request._reply (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:455:10)
    at Items.serial (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:389:21)
    at done (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:31:25)
    at finalize (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/handler.js:21:16)
    at Hoek.once (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/protect.js:52:16)
    at wrapped (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
    at finalize (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/handler.js:82:20)
    at Function.wrapped [as _next] (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
  log   [10:41:25.247] [info][status][Sentinl] No indices found, Initializing
  log   [10:41:55.250] [info][status][Sentinl] No indices found, Initializing
  log   [10:42:25.251] [info][status][Sentinl] No indices found, Initializing
  log   [10:42:55.252] [info][status][Sentinl] No indices found, Initializing
  log   [10:43:25.254] [info][status][Sentinl] No indices found, Initializing
  log   [10:43:55.257] [info][status][Sentinl] No indices found, Initializing
  log   [10:44:25.257] [info][status][Sentinl] No indices found, Initializing
  log   [10:44:55.258] [info][status][Sentinl] No indices found, Initializing
  log   [10:44:58.199] [info][status][Sentinl] Saving scripts with type: condition
  log   [10:45:25.260] [info][status][Sentinl] No indices found, Initializing
  log   [10:45:55.266] [info][status][Sentinl] No indices found, Initializing
  log   [10:46:25.264] [info][status][Sentinl] No indices found, Initializing
  log   [10:46:55.268] [info][status][Sentinl] No indices found, Initializing
got an error [404] Not Found
  log   [10:47:16.000] [warning][process] TypeError: this._next is not a function
    at Function.internals.continue (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/reply.js:108:10)
    at server.ext (/home/test/elk/kibana-5.4.1-linux-x86_64/plugins/readonlyrest_kbn/server/routes/lib/auth.js:6:2315)
    at Items.serial (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:403:22)
    at iterate (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at Function.wrapped [as _next] (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
    at Function.internals.continue (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/reply.js:108:10)
    at /home/test/elk/kibana-5.4.1-linux-x86_64/src/server/http/index.js:121:28
    at Items.serial (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:403:22)
    at iterate (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:39:9)
    at _protect.run (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:398:15)
    at internals.Protect.run (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/protect.js:64:5)
    at internals.Request._invoke (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:396:19)
    at internals.Request._reply (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:455:10)
    at Items.serial (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:389:21)
    at done (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:31:25)
    at finalize (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/handler.js:21:16)
    at Hoek.once (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/protect.js:52:16)
    at wrapped (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
    at finalize (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/handler.js:82:20)
    at Function.wrapped [as _next] (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
  log   [10:47:16.078] [info][status][Sentinl] Get scripts with type: transform
  log   [10:47:16.081] [info][status][Sentinl] Get scripts with type: input
  log   [10:47:16.083] [info][status][Sentinl] Get scripts with type: condition
  log   [10:47:25.266] [info][status][Sentinl] No indices found, Initializing
  log   [10:47:55.271] [info][status][Sentinl] No indices found, Initializing
  log   [10:48:25.273] [info][status][Sentinl] No indices found, Initializing
  log   [10:48:55.273] [info][status][Sentinl] No indices found, Initializing
got an error [404] Not Found
  log   [10:49:17.658] [warning][process] TypeError: this._next is not a function
    at Function.internals.continue (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/reply.js:108:10)
    at server.ext (/home/test/elk/kibana-5.4.1-linux-x86_64/plugins/readonlyrest_kbn/server/routes/lib/auth.js:6:2315)
    at Items.serial (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:403:22)
    at iterate (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at Function.wrapped [as _next] (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
    at Function.internals.continue (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/reply.js:108:10)
    at /home/test/elk/kibana-5.4.1-linux-x86_64/src/server/http/index.js:121:28
    at Items.serial (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:403:22)
    at iterate (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:39:9)
    at _protect.run (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:398:15)
    at internals.Protect.run (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/protect.js:64:5)
    at internals.Request._invoke (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:396:19)
    at internals.Request._reply (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:455:10)
    at Items.serial (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/request.js:389:21)
    at done (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:31:25)
    at finalize (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/handler.js:21:16)
    at Hoek.once (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/protect.js:52:16)
    at wrapped (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
    at finalize (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/lib/handler.js:82:20)
    at Function.wrapped [as _next] (/home/test/elk/kibana-5.4.1-linux-x86_64/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
  log   [10:49:17.698] [info][status][Sentinl] Get scripts with type: transform
  log   [10:49:17.734] [info][status][Sentinl] Get scripts with type: input
  log   [10:49:17.746] [info][status][Sentinl] Get scripts with type: condition
  log   [10:49:25.275] [info][status][Sentinl] No indices found, Initializing
  log   [10:49:55.279] [info][status][Sentinl] No indices found, Initializing

**Comment by shubhamverma27** [comment]
@lmangani  These logs are coming even if I use elastic search authentication id in my kibana.
Also, The watcher is not working I think.as I am not getting any alerts/reports on the default example too.

**Comment by shubhamverma27** [comment]
@lmangani  Please Help fast if possible :)

**Comment by lmangani** [comment]
@shubhamverma27 your logs are saying kibana-5.4.1 - which version are you using, and what plugin version did you install?

**Comment by shubhamverma27** [comment]
@lmangani Hi, I figured it out ..Added exception for POST AND GET etc. for sentinl in readonlyrest..
It would be great to add multi user capabilities in Sentinl ie different user accessing different specific watchers etc.


Also How do I out put the value of a specific filed in the message body 
for ex i am comparing browsermajor > 45 in script and want to write in message the browsermajor like  {{browsermajor}} and it should give its current value. but this doesnt work..whats the correct syntax???

**Comment by lmangani** [comment]
@shubhamverma27 please share the settings for others to use - also kindly open a separate issue to troubleshoot the body message composition and mustache templating

**Comment by shubhamverma27** [comment]
These are the setting to allow Sentinl access through readonlyrest       
    - name: ALLOWPOST
      type: allow
      methods: [POST,HEAD,GET,DELETE,OPTIONS]
      uri_re:  ^/watcher_alarms-.*/
      hosts: [localhost] 
      verbosity: info
 
    - name: ALLOWHEAD
      type: allow
      methods: [POST,HEAD,GET,DELETE]
      uri_re:  ^/watcher.*/
      hosts: [localhost] 
      verbosity: info

**Comment by lmangani** [comment]
@shubhamverma27 thanks, added to our Wiki/FAQ: https://github.com/sirensolutions/sentinl/wiki/SENTINL-FAQ#q-how-can-i-use-sentinl-with-readonlyrest-authentication

**Comment by shubhamverma27** [comment]
Hi, Please also add that an exception for each index to be watched has to be made in readonlyrest!
