### ISSUE TITLE
msg Reporting Disabled! Email Required!

### ISSUE THREAD

**Issue by jmreymond** [sirensolutions/sentinl#215]
1. Issue Description

I do not receive emails and I have this message in the log file

` [info][status][Sentinl][report] Reporting Disabled! Email Required!`

2. Reproducing the Issue step-by-step
build a new reporter, Action/Add action/Report and set From and To emails

3. Expected Results vs. Actual Results
receive en email vs nothing received
4. Additional Details
In plugins/sentinl/server/lib/actions.js , I am looking for the message error : line 140 and I do not understand.

```
   139        if (!emailServer || !config.settings.email.active) {
   140          server.log(['status', 'info', 'Sentinl', 'email'], 'Delivery Disabled!');
   141        }
```

kibana.yml is updated with a sentinl section for email parameters and thzreport action has From and TO fields filled. No messages in /var/log/messages or /var/log/maillog
Is it possible to debug more precisely ?
Thanks for your tips

**Comment by lmangani** [comment]
Hi @jmreymond What version of Kibana and SENTINL are you using?
The Report action does indeed require a fully working email setup. Are simple email notifications working? I'd suggest testing those ahead of reports just to be sure.

Could you confirm is settings email is actually enabled?
```
sentinl:
  settings:
    email:
      active: true
```
If all of the above is true, please set log level to ```debug``` and check for additional output. Thanks!

**Comment by jmreymond** [comment]
thanks for your fast answer:

my configuration in kibana.yml

```
sentinl:
  settings:
    email:
      active: true
      user: foo
      password: foo
      host: smtpappsie.sirisxxx..fr
      ssl: false
    report:
      active: true
      tmp_path: /tmp
```
It seems OK, so how to set log level to debug ?

**Comment by sergibondarenko** [comment]
@jmreymond Your config is fine.

The status `[info][status][Sentinl][report] Reporting Disabled! Email Required!` means that Sentinl was not able to initiate the connection to your email server. Please check your server using some email client, for example `mailx`:
```
mailx -S smtp=<smtp-server-address> -r <from-address> -s <subject> -v <to-address> < body.txt
```  

To enable debug, put `logging.verbose: true` in kibana.yml.

**Comment by jmreymond** [comment]
The test with mailx is OK and I receive my email
So, debug in kibana.yml
and 

```
{"type":"log","@timestamp":"2017-09-26T14:35:57Z","tags":["plugin","debug"],"pid":19358,"message":"Checking Elasticsearch version"}
{"type":"ops","@timestamp":"2017-09-26T14:35:58Z","tags":[],"pid":19358,"os":{"load":[0.75244140625,0.43994140625,0.2041015625],"mem":{"total
":16659128320,"free":7523258368},"uptime":1226495},"proc":{"uptime":72.845,"mem":{"rss":122298368,"heapTotal":95485952,"heapUsed":79877480,"e
xternal":130039},"delay":0.38413095474243164},"load":{"requests":{},"concurrents":{"25603":0},"responseTimes":{},"sockets":{"http":{"total":0
},"https":{"total":0}}},"message":"memory: 76.2MB uptime: 0:01:13 load: [0.75 0.44 0.20] delay: 0.384"}
{"type":"log","@timestamp":"2017-09-26T14:35:59Z","tags":["plugin","debug"],"pid":19358,"message":"Checking Elasticsearch version"}
{"type":"log","@timestamp":"2017-09-26T14:36:00Z","tags":["status","info","Sentinl","scheduler"],"pid":19358,"message":"Executing watcher: pr
0we4mhj1-3ng5gk4plwl-w2tc0gwk92"}
{"type":"log","@timestamp":"2017-09-26T14:36:00Z","tags":["status","debug","Sentinl","scheduler"],"pid":19358,"message":"{ _index: 'watcher',
\n  _type: 'sentinl-watcher',\n  _id: 'pr0we4mhj1-3ng5gk4plwl-w2tc0gwk92',\n  _score: 1,\n  _source: \n   { title: 'Report F5 Prod',\n     di
sable: false,\n     report: true,\n     trigger: { schedule: [Object] },\n     condition: { script: [Object] },\n     transform: { script: [O
bject] },\n     actions: { 'report F5 en Prod': [Object] } } }"}
{"type":"log","@timestamp":"2017-09-26T14:36:00Z","tags":["status","info","Sentinl","scheduler"],"pid":19358,"message":"Executing report acti
on: pr0we4mhj1-3ng5gk4plwl-w2tc0gwk92"}
{"type":"log","@timestamp":"2017-09-26T14:36:00Z","tags":["status","info","Sentinl"],"pid":19358,"message":"Processing action: report F5 en P
rod"}
{"type":"log","@timestamp":"2017-09-26T14:36:00Z","tags":["status","info","Sentinl","report"],"pid":19358,"message":"Subject: Sentinl Report
enfin pour F5/Prod, Body: Sample Sentinl Screenshot Report\nEnfin, cela fonctionne"}
{"type":"log","@timestamp":"2017-09-26T14:36:00Z","tags":["
```status","info","Sentinl","report"],"pid":19358,"message":"Reporting Disabled! Email Required!"}

very mysterious...

**Comment by lmangani** [comment]
Indeed... are you using the very latest snapshot for your version?

**Comment by lmangani** [comment]
The actual root cause error will be closer to the startup of SENTINL, where the ```emailServer``` is [initialized](https://github.com/sirensolutions/sentinl/blob/5dfda8b0fe023c40d97ae59252f40f0b7ceb81dd/server/lib/actions.js#L52).

**Comment by jmreymond** [comment]
I am running the master of 5.5.2 sentinl

```
bin/kibana-plugin install file:///tmpinst/sentinl-v5.5.2.zip
Attempting to transfer from file:///tmpinst/sentinl-v5.5.2.zip
Transferring 116259694 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete

```

Unfortunatly, I cannot install from 5.5 branch

```
bin/kibana-plugin remove sentinl
Removing sentinl...
<CELIST0031:1> (root)/usr/share/kibana-pirate# bin/kibana-plugin install file:///tmpinst/sentinl-branch-5.5.zip
Attempting to transfer from file:///tmpinst/sentinl-branch-5.5.zip
Transferring 82894311 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

```

my log file with debug on

[sentinl.txt](https://github.com/sirensolutions/sentinl/files/1333673/sentinl.txt)

**Comment by lmangani** [comment]
According to the logs, emailjs is never initialized or we would see a log entry for it.
The condition failing is ```config.settings.email.active``` as if active wasn't set at all.... are you able to send an email notification to confirm?

**Comment by sergibondarenko** [comment]
@jmreymond it is ok to not install Sentinl from branch, correct way is installing a .zip specific to your Kibana version https://github.com/sirensolutions/sentinl#app-installation

**Comment by jmreymond** [comment]
I have removed kibana and sentinel for a fresh, new install. Now, I have a crash :-(
My configuration yml

```
sentinl:
  settings:
    email:
      active: true
      user: foo
      password: foo
      host: smtpappsie.sirissie.fr
      ssl: false
    report:
      active: true
      tmp_path: /tmp
```
and the crash in the log file

```
/usr/share/kibana-pirate/plugins/sentinl/node_modules/emailjs/smtp/smtp.js:483
            if ((self.features.auth || "").indexOf(preferred[i]) != -1) {
                                           ^

TypeError: (self.features.auth || "").indexOf is not a function
    at initiate (/usr/share/kibana-pirate/plugins/sentinl/node_modules/emailjs/smtp/smtp.js:483:44)
    at caller (/usr/share/kibana-pirate/plugins/sentinl/node_modules/emailjs/smtp/smtp.js:48:14)
    at attempt (/usr/share/kibana-pirate/plugins/sentinl/node_modules/emailjs/smtp/smtp.js:415:14)
    at caller (/usr/share/kibana-pirate/plugins/sentinl/node_modules/emailjs/smtp/smtp.js:48:14)
    at response (/usr/share/kibana-pirate/plugins/sentinl/node_modules/emailjs/smtp/smtp.js:345:13)
    at caller (/usr/share/kibana-pirate/plugins/sentinl/node_modules/emailjs/smtp/smtp.js:48:14)
    at response (/usr/share/kibana-pirate/plugins/sentinl/node_modules/emailjs/smtp/smtp.js:201:11)
    at caller (/usr/share/kibana-pirate/plugins/sentinl/node_modules/emailjs/smtp/smtp.js:48:14)
    at Socket.response (/usr/share/kibana-pirate/plugins/sentinl/node_modules/emailjs/smtp/smtp.js:181:11)
    at Socket.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at notify (/usr/share/kibana-pirate/plugins/sentinl/node_modules/emailjs/smtp/response.js:19:14)
    at Socket.watch (/usr/share/kibana-pirate/plugins/sentinl/node_modules/emailjs/smtp/response.js:44:7)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```
So, I removed user and password in my configuration and now, it works :-) 
thanks for your answers

**Comment by jmreymond** [comment]
And now, it works nicely !
Great job, guys :-)

**Comment by alankrat-daga-guavus** [comment]
report output:
{
  "@timestamp": "2018-09-12T06:29:06.618Z",
  "error": true,
  "report": false,
  "watcher": "watcher_titlee",
  "level": "high",
  "message": "html email action: Error: email delivery disabled",
  "payload": {},
  "attachment": {}
}
