### ISSUE TITLE
Sentinl installation throwing error cannot find module 'elasticsearch'

### ISSUE THREAD

**Issue by manya12** [sirensolutions/sentinl#216]
I have elasticsearch and kibana 5.5.1 installed on my machine. I am trying to install senitnl.
When i am running the command /usr/share/kibana/bin/kibana-plugin install file://`pwd`/target/gulp/sentinl.zip
It throws an error:
module.js:471
    throw err;
    ^

Error: Cannot find module 'elasticsearch'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/kibana/src/server/saved_objects/client/lib/handle_es_error.js:8:22)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/share/kibana/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/kibana/src/server/saved_objects/client/lib/index.js:16:24)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/share/kibana/node_modules/babel-register/lib/node.js:152:7)

Please help me with this

**Comment by sergibondarenko** [comment]
@manya12 please try this Sentinl https://github.com/sirensolutions/sentinl/releases/download/tag-5.5/sentinl-v5.5.1.zip

**Comment by lmangani** [comment]
Closing, please comment to re-open if needed.
