### ISSUE TITLE
sentinl and kibana 5.5.3

### ISSUE THREAD

**Issue by jmreymond** [sirensolutions/sentinl#223]
1. Issue Description
I have to upgrade to kibana 5.5.3 due to the nasty bug https://github.com/elastic/kibana/pull/13830
When I install sentil, I have the message
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [sentinl]. Expected [5.5.3]; found [5.5.2]"

2. Reproducing the Issue step-by-step
upgrade to kibana 5.5.3 with yum install
install sentinl
3. Expected Results vs. Actual Results

4. Additional Details
please can you provide
https://github.com/sirensolutions/sentinl/releases/download/tag-5.5/sentinl-v5.5.3.zip
thanks,

**Comment by sergibondarenko** [comment]
@jmreymond The Sentinl 5.5.3 release is ready https://github.com/sirensolutions/sentinl/releases/download/tag-5.5/sentinl-v5.5.3.zip

**Comment by jmreymond** [comment]
thansK;
installation is ok but now, stranges messages as

```
log   [09:22:46.438] [info][status][Sentinl] Saving Watcher with ID: imx6x58ri9-0wnacfpwfs6d-l65mkyqozcc
Unhandled rejection Error: Cannot provide statusCode or message with boom error
    at Object.exports.assert (/usr/share/kibana-pirate/plugins/sentinl/node_modules/hoek/lib/index.js:736:11)
    at Object.exports.wrap (/usr/share/kibana-pirate/plugins/sentinl/node_modules/boom/lib/index.js:76:10)
    at Object.internals.create (/usr/share/kibana-pirate/plugins/sentinl/node_modules/boom/lib/index.js:94:24)
    at Object.exports.unauthorized (/usr/share/kibana-pirate/plugins/sentinl/node_modules/boom/lib/index.js:164:27)
    at handleESError (/usr/share/kibana-pirate/plugins/sentinl/server/lib/handle_es_error.js:47:21)
    at callWithRequest.then.then.catch.err (/usr/share/kibana-pirate/plugins/sentinl/server/routes/routes.js:245:29)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/usr/share/kibana-pirate/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/share/kibana-pirate/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/share/kibana-pirate/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/usr/share/kibana-pirate/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/share/kibana-pirate/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/share/kibana-pirate/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/share/kibana-pirate/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5
```)

**Comment by sergibondarenko** [comment]
@jmreymond can you save and execute a watcher?

**Comment by sergibondarenko** [comment]
@jmreymond do you see any error in the Sentinl UI?

**Comment by jmreymond** [comment]
no message in the Sentinl UI but run every is empty and throttle is empty
![screenshot-2017-10-4 kibana 1](https://user-images.githubusercontent.com/8809413/31169227-3f85fb82-a8f8-11e7-9031-e588425d0c1d.png)
![screenshot-2017-10-4 kibana](https://user-images.githubusercontent.com/8809413/31169226-3f81efec-a8f8-11e7-9e1a-5c29bdd890ea.png)

**Comment by sergibondarenko** [comment]
@jmreymond I've created an issue for this https://github.com/sirensolutions/sentinl/issues/225
The issue will be solved soon.
