### ISSUE TITLE
Cannot provide statusCode or message with boom error

### ISSUE THREAD

**Issue by sergibondarenko** [sirensolutions/sentinl#225]
Original https://github.com/sirensolutions/sentinl/issues/223#issuecomment-334099049
@jmreymond
installation is ok but now, stranges messages as

```
log   [09:22:46.438] [info][status][Sentinl] Saving Watcher with ID: imx6x58ri9-0wnacfpwfs6d-l65mkyqozcc
Unhandled rejection Error: Cannot provide statusCode or message with boom error
    at Object.exports.assert (/usr/share/kibana-pirate/plugins/sentinl/node_modules/hoek/lib/index.js:736:11)
    at Object.exports.wrap (/usr/share/kibana-pirate/plugins/sentinl/node_modules/boom/lib/index.js:76:10)
    at Object.internals.create (/usr/share/kibana-pirate/plugins/sentinl/node_modules/boom/lib/index.js:94:24)
    at Object.exports.unauthorized (/usr/share/kibana-pirate/plugins/sentinl/node_modules/boom/lib/index.js:164:27)
    at handleESError (/usr/share/kibana-pirate/plugins/sentinl/server/lib/handle_es_error.js:47:21)
    at callWithRequest.then.then.catch.err (/usr/share/kibana-pirate/plugins/sentinl/server/routes/routes.js:245:29)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/usr/share/kibana-pirate/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/share/kibana-pirate/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/share/kibana-pirate/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/usr/share/kibana-pirate/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/share/kibana-pirate/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/share/kibana-pirate/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/share/kibana-pirate/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5
```)

**Comment by sergibondarenko** [comment]
@jmreymond I've just done a fresh Kibana 5.5.3 and Sentinl 5.5.3  installation. And I don't have the error. Also, I was able to create and execute a watcher. 
Please remove Kibana Webpack bundles and restart Kibana.
```
rm -rf kibana/optimize/bundles/*
```
I think you have some old cold build there which causes the error. The bundles will be generated again when you start Kibana.

**Comment by jmreymond** [comment]
sorry, but same issue

```
<CELIST0031:1> (root)/usr/share/kibana-pirate# rm -rf optimize/bundles/*
<CELIST0031:1> (root)/usr/share/kibana-pirate# bin/kibana -c /etc/kibana/kibana-pirate.yml
  log   [09:00:25.322] [info][optimize] Optimizing and caching bundles for sentinl, kibana, stateSessionStorageRedirect, timelion and status_page. This may take a few minutes
  log   [09:04:00.018] [info][optimize] Optimization of bundles for sentinl, kibana, stateSessionStorageRedirect, timelion and status_page complete in 214.69 seconds
  log   [09:04:00.120] [info][status][plugin:kibana@5.5.3] Status changed from uninitialized to green - Ready
  log   [09:04:00.300] [info][status][plugin:elasticsearch@5.5.3] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [09:04:00.362] [info][status][plugin:sentinl@5.5.2-SNAPSHOT] Status changed from uninitialized to green - Ready
  log   [09:04:00.413] [warning] You're running Kibana 5.5.3 with some different versions of Elasticsearch. Update Kibana or Elasticsearch to the same version to prevent compatibility issues: v5.5.2 @ 126.200.128.223:9200 (126.200.128.223), v5.5.2 @ 126.200.128.221:9200 (126.200.128.221), v5.5.2 @ 126.200.128.224:9200 (126.200.128.224), v5.5.2 @ 126.200.128.222:9200 (126.200.128.222)
  log   [09:04:00.417] [info][status][plugin:metrics@5.5.3] Status changed from uninitialized to green - Ready
  log   [09:04:00.740] [info][status][plugin:timelion@5.5.3] Status changed from uninitialized to green - Ready
  log   [09:04:00.747] [info][listening] Server running at https://0.0.0.0:25603
  log   [09:04:00.749] [info][status][ui settings] Status changed from uninitialized to yellow - Elasticsearch plugin is yellow
  log   [09:04:00.759] [info][status][plugin:elasticsearch@5.5.3] Status changed from yellow to green - Kibana index ready
  log   [09:04:00.764] [info][status][Sentinl] Sentinl Initializing
  log   [09:04:00.829] [info][status][Sentinl] Checking watcher index ...
  log   [09:04:00.834] [info][status][Sentinl] Checking watcher index type sentinl-script ...
  log   [09:04:00.836] [info][status][Sentinl] Checking watcher_alarms index ...
  log   [09:04:00.844] [info][status][ui settings] Status changed from yellow to green - Ready
  log   [09:04:00.854] [info][status][Sentinl][report] Phantom installed at /usr/share/kibana-pirate/plugins/sentinl/phantomjs/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
  log   [09:04:25.863] [info][status][Sentinl][scheduler] server.sentinlStore.scheduled Watch: pr0we4mhj1-3ng5gk4plwl-w2tc0gwk92 every every 3 mins
  log   [09:04:25.870] [info][status][Sentinl][scheduler] server.sentinlStore.scheduled Watch: qkqofcp4asq-s2xngvwxe2f-tg6rx28gz0i every every 5 mins
Unhandled rejection Error: Cannot provide statusCode or message with boom error
    at Object.exports.assert (/usr/share/kibana-pirate/plugins/sentinl/node_modules/hoek/lib/index.js:736:11)
    at Object.exports.wrap (/usr/share/kibana-pirate/plugins/sentinl/node_modules/boom/lib/index.js:76:10)
    at Object.internals.create (/usr/share/kibana-pirate/plugins/sentinl/node_modules/boom/lib/index.js:94:24)
    at Object.exports.unauthorized (/usr/share/kibana-pirate/plugins/sentinl/node_modules/boom/lib/index.js:164:27)
    at handleESError (/usr/share/kibana-pirate/plugins/sentinl/server/lib/handle_es_error.js:47:21)
    at callWithRequest.then.catch.err (/usr/share/kibana-pirate/plugins/sentinl/server/routes/routes.js:140:29)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/usr/share/kibana-pirate/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/share/kibana-pirate/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/share/kibana-pirate/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/usr/share/kibana-pirate/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/share/kibana-pirate/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/share/kibana-pirate/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/share/kibana-pirate/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  log   [09:04:41.732] [info][status][Sentinl] Get scripts with type: input
  log   [09:04:41.736] [info][status][Sentinl] Get scripts with type: condition
  log   [09:04:41.739] [info][status][Sentinl] Get scripts with type: transform
Unhandled rejection Error: Cannot provide statusCode or message with boom error
    at Object.exports.assert (/usr/share/kibana-pirate/plugins/sentinl/node_modules/hoek/lib/index.js:736:11)
    at Object.exports.wrap (/usr/share/kibana-pirate/plugins/sentinl/node_modules/boom/lib/index.js:76:10)
    at Object.internals.create (/usr/share/kibana-pirate/plugins/sentinl/node_modules/boom/lib/index.js:94:24)
    at Object.exports.unauthorized (/usr/share/kibana-pirate/plugins/sentinl/node_modules/boom/lib/index.js:164:27)
    at handleESError (/usr/share/kibana-pirate/plugins/sentinl/server/lib/handle_es_error.js:47:21)
    at callWithRequest.then.catch.err (/usr/share/kibana-pirate/plugins/sentinl/server/routes/routes.js:59:25)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/usr/share/kibana-pirate/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/share/kibana-pirate/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/share/kibana-pirate/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/usr/share/kibana-pirate/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/share/kibana-pirate/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/share/kibana-pirate/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/share/kibana-pirate/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  log   [09:04:45.212] [info][status][Sentinl] Get scripts with type: input
Unhandled rejection Error: Cannot provide statusCode or message with boom error
    at Object.exports.assert (/usr/share/kibana-pirate/plugins/sentinl/node_modules/hoek/lib/index.js:736:11)
    at Object.exports.wrap (/usr/share/kibana-pirate/plugins/sentinl/node_modules/boom/lib/index.js:76:10)
    at Object.internals.create (/usr/share/kibana-pirate/plugins/sentinl/node_modules/boom/lib/index.js:94:24)
    at Object.exports.unauthorized (/usr/share/kibana-pirate/plugins/sentinl/node_modules/boom/lib/index.js:164:27)
    at handleESError (/usr/share/kibana-pirate/plugins/sentinl/server/lib/handle_es_error.js:47:21)
    at callWithRequest.then.catch.err (/usr/share/kibana-pirate/plugins/sentinl/server/routes/routes.js:140:29)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/usr/share/kibana-pirate/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/share/kibana-pirate/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/share/kibana-pirate/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/usr/share/kibana-pirate/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/share/kibana-pirate/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/share/kibana-pirate/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/share/kibana-pirate/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  log   [09:04:45.272] [info][status][Sentinl] Get scripts with type: condition
  log   [09:04:45.275] [info][status][Sentinl] Get scripts with type: transform
  log   [09:04:55.857] [info][status][Sentinl][scheduler] Clearing watcher: pr0we4mhj1-3ng5gk4plwl-w2tc0gwk92
  log   [09:04:55.858] [info][status][Sentinl][scheduler] server.sentinlStore.scheduled Watch: pr0we4mhj1-3ng5gk4plwl-w2tc0gwk92 every every 3 mins
  log   [09:04:55.858] [info][status][Sentinl][scheduler] Clearing watcher: qkqofcp4asq-s2xngvwxe2f-tg6rx28gz0i
  log   [09:04:55.859] [info][status][Sentinl][scheduler] server.sentinlStore.scheduled Watch: qkqofcp4asq-s2xngvwxe2f-tg6rx28gz0i every every 5 mins
```

**Comment by jmreymond** [comment]
If you want, I can install a new kibana with sentinl

**Comment by jmreymond** [comment]
with Chrome debugger, I have a message 

```
https://celist0031:25603/api/sentinl/list
Failed to load resource: net::ERR_EMPTY_RESPONSE
commons.bundle.js?v=15460:38 TypeError: Cannot read property 'message' of null
    at formatMsg (commons.bundle.js?v=15460:70)
    at Notifier.error (commons.bundle.js?v=15460:70)
    at wrapper (commons.bundle.js?v=15460:2)
    at processQueue (commons.bundle.js?v=15460:38)
    at commons.bundle.js?v=15460:38
    at Scope.$eval (commons.bundle.js?v=15460:39)
    at Scope.$digest (commons.bundle.js?v=15460:39)
    at Scope.$apply (commons.bundle.js?v=15460:39)
    at done (commons.bundle.js?v=15460:37)
    at completeRequest (commons.bundle.js?v=15460:37)
```

**Comment by sergibondarenko** [comment]
>If you want, I can install a new kibana with sentinl but basically, it is done with kibana 5.5.3 and the associated plugin sentinl

@jmreymond yes, try with a fresh Kibana installation and we will see.

**Comment by jmreymond** [comment]
no improvements :-(

**Comment by jmreymond** [comment]
tested with IE11 and in navigator console

```
Error: Argument non valide.
   at Anonymous function (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:37:6069)
   at Anonymous function (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:38:534)
   at Anonymous function (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:38:31626)
   at Scope.prototype.$digest (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:39:2869)
   at Scope.prototype.$apply (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:39:5026)
   at done (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:37:25016)
   at completeRequest (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:37:28702)
   at xhr.onload (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:37:29634)
Error: Argument non valide.
   at Anonymous function (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:37:6069)
   at Anonymous function (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:38:534)
   at Anonymous function (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:38:31626)
   at Scope.prototype.$digest (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:39:2869)
   at Scope.prototype.$apply (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:39:5026)
   at done (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:37:25016)
   at completeRequest (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:37:28702)
   at xhr.onload (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:37:29634)
Error: Argument non valide.
   at Anonymous function (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:37:6069)
   at Anonymous function (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:38:534)
   at Anonymous function (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:38:31626)
   at Scope.prototype.$digest (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:39:2869)
   at Scope.prototype.$apply (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:39:5026)
   at done (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:37:25016)
   at completeRequest (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:37:28702)
   at xhr.onload (https://celist0031.sigcesie.caisse-epargne.fr:25603/bundles/commons.bundle.js?v=15460:37:29634)


```
I suppose Kibana 5.5.3 is completely broken so I think it is better to switch back to Kibana 5.5.2
Your opinion ?

**Comment by sergibondarenko** [comment]
@jmreymond do you use Elasticsearch 5.5.3 too? Try with it if not, Kibana 5.5.3 + Elasticsearch 5.5.3.

**Comment by jmreymond** [comment]
sorry for this late answer :-( 
I am looking for a little elasticsearch instance in 5.5.3 since we are back to 5.5.2 because kibana 5.5.3 is too buggy (and we sacrifice IE compatibility)

**Comment by lmangani** [comment]
Closing. Please comment to re-open if required.
