### ISSUE TITLE
Reporter broken for stringent smtp server (SES)  

### ISSUE THREAD

**Issue by robertjustjones** [sirensolutions/sentinl#266]
1. Issue Description

When setting up a Reporter with Amazon SES as the smtp server, I'm getting an error on the smtp send with the attachment. Regular watched alerts are going through just fine, only when attachments (png pr pdf) are involved.  Here it is when running in dev mode:

```
server    log   [21:33:40.477] [error][status][Sentinl][report] Error: bad response on command '
.': Transaction failed: Expected ';', got ":"
    at module.exports (.../kibana/plugins/sentinl/node_modules/emailjs/smtp/error.js:3:13)
    at response (.../kibana/plugins/sentinl/node_modules/emailjs/smtp/smtp.js:207:28)
    at caller (.../kibana/plugins/sentinl/node_modules/emailjs/smtp/smtp.js:48:14)
    at TLSSocket.response (.../kibana/plugins/sentinl/node_modules/emailjs/smtp/smtp.js:181:11)
    at TLSSocket.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at TLSSocket.emit (events.js:191:7)
    at notify (.../kibana/plugins/sentinl/node_modules/emailjs/smtp/response.js:19:14)
    at TLSSocket.watch (.../kibana/plugins/sentinl/node_modules/emailjs/smtp/response.js:44:7)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:547:20)
```

2. Reproducing the Issue step-by-step

3. Expected Results vs. Actual Results

The email should go through without error.

4. Additional Details

I've traced it to a non-spec line in the mime:

```
Content-Disposition: attachment; filename=cid:my-report
```
should be
```
Content-Disposition: attachment; filename="cid:my-report"
```

**Comment by lmangani** [comment]
Thanks for the PR! Will be included in upcoming releases.
