### ISSUE TITLE
Cannot access Kibana anymore after started a watcher.

### ISSUE THREAD

**Issue by matteobaire** [sirensolutions/sentinl#299]
Hello, I tried to set a watcher in order to find all hits for a specific _type in the input query. I ended up putting a query like "hit":{"index": "something", "type": "something"} under input (unfortunately I can't be more precise because i can't access kibana anymore)

Since I did something wrong I expected to get an error cliens-side or, at least, to be able to delete the watcher, instead now I can't connect to the server from remote.

I'd like to know how I can delete the broken watcher server side

Server side I get this error:

```
 Error: Watcher search request is malformed: svpa9s93ggh-j3c029abuvc-q6819vfnt5
    at Watcher.execute (/usr/share/kibana/plugins/sentinl/server/lib/classes/watcher.js:177:15)
    at watching (/usr/share/kibana/plugins/sentinl/server/lib/scheduler.js:70:13)
    at /usr/share/kibana/plugins/sentinl/server/lib/scheduler.js:104:7
    at Timeout.scheduleTimeout [as _onTimeout] (/usr/share/kibana/plugins/sentinl/node_modules/later/later.js:846:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

and this is what I get from stdout:
```
{"type":"response","@timestamp":"2018-01-25T19:15:55Z","tags":[],"pid":1125,"method":"get","statusCode":304,"req":{"url":"/ui/fonts/open_sans/open_sans_v13_latin_300.woff2","method":"get","headers":{"host":"host-index","connection":"keep-alive","origin":"http://host-index","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 OPR/50.0.2762.58","accept":"*/*","referer":"http://host-index/app/kibana","accept-encoding":"gzip, deflate","accept-language":"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7","if-none-match":"\"2da4d6d1b1bef32c05719680145b61613b3829b4\"","if-modified-since":"Thu, 07 Sep 2017 03:21:10 GMT"},"remoteAddress":"217.133.19.16","userAgent":"217.133.19.16","referer":"http://host-index/app/kibana"},"res":{"statusCode":304,"responseTime":9,"contentLength":9},"message":"GET /ui/fonts/open_sans/open_sans_v13_latin_300.woff2 304 9ms - 9.0B"}
{"type":"response","@timestamp":"2018-01-25T19:15:55Z","tags":[],"pid":1125,"method":"get","statusCode":200,"req":{"url":"/ui/favicons/favicon-32x32.png","method":"get","headers":{"host":"host-index","connection":"keep-alive","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 OPR/50.0.2762.58","accept":"image/webp,image/apng,image/,/*;q=0.8","referer":"http://host-index/app/kibana","accept-encoding":"gzip, deflate","accept-language":"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7"},"remoteAddress":"217.133.19.16","userAgent":"217.133.19.16","referer":"http://host-index/app/kibana"},"res":{"statusCode":200,"responseTime":5,"contentLength":9},"message":"GET /ui/favicons/favicon-32x32.png 200 5ms - 9.0B"}
{"type":"response","@timestamp":"2018-01-25T19:15:55Z","tags":[],"pid":1125,"method":"get","statusCode":200,"req":{"url":"/bundles/commons.style.css?v=15523","method":"get","headers":{"host":"host-index","connection":"keep-alive","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 OPR/50.0.2762.58","accept":"text/css,/*;q=0.1","referer":"http://host-index/app/kibana","accept-encoding":"gzip, deflate","accept-language":"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7"},"remoteAddress":"217.133.19.16","userAgent":"217.133.19.16","referer":"http://host-index/app/kibana"},"res":{"statusCode":200,"responseTime":61,"contentLength":9},"message":"GET /bundles/commons.style.css?v=15523 200 61ms - 9.0B"}
{"type":"response","@timestamp":"2018-01-25T19:15:55Z","tags":[],"pid":1125,"method":"get","statusCode":200,"req":{"url":"/bundles/kibana.style.css?v=15523","method":"get","headers":{"host":"host-index","connection":"keep-alive","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 OPR/50.0.2762.58","accept":"text/css,/*;q=0.1","referer":"http://host-index/app/kibana","accept-encoding":"gzip, deflate","accept-language":"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7"},"remoteAddress":"217.133.19.16","userAgent":"217.133.19.16","referer":"http://host-index/app/kibana"},"res":{"statusCode":200,"responseTime":55,"contentLength":9},"message":"GET /bundles/kibana.style.css?v=15523 200 55ms - 9.0B"}
{"type":"response","@timestamp":"2018-01-25T19:15:55Z","tags":[],"pid":1125,"method":"get","statusCode":200,"req":{"url":"/ui/favicons/favicon-16x16.png","method":"get","headers":{"host":"host-index","connection":"keep-alive","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 OPR/50.0.2762.58","accept":"image/webp,image/apng,image/,/*;q=0.8","referer":"http://host-index/app/kibana","accept-encoding":"gzip, deflate","accept-language":"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7"},"remoteAddress":"217.133.19.16","userAgent":"217.133.19.16","referer":"http://host-index/app/kibana"},"res":{"statusCode":200,"responseTime":2,"contentLength":9},"message":"GET /ui/favicons/favicon-16x16.png 200 2ms - 9.0B"}
{"type":"log","@timestamp":"2018-01-25T19:15:55Z","tags":["status","info","Sentinl","scheduler"],"pid":1125,"message":"server.sentinlStore.scheduled Watch: svpa9s93ggh-j3c029abuvc-q6819vfnt5 every after 5:00 before 20:00"}
{"type":"response","@timestamp":"2018-01-25T19:15:55Z","tags":[],"pid":1125,"method":"get","statusCode":200,"req":{"url":"/ui/favicons/favicon.ico","method":"get","headers":{"host":"host-index","connection":"keep-alive","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 OPR/50.0.2762.58","accept":"image/webp,image/apng,image/,/*;q=0.8","referer":"http://host-index/app/kibana","accept-encoding":"gzip, deflate","accept-language":"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7"},"remoteAddress":"217.133.19.16","userAgent":"217.133.19.16","referer":"http://host-index/app/kibana"},"res":{"statusCode":200,"responseTime":7,"contentLength":9},"message":"GET /ui/favicons/favicon.ico 200 7ms - 9.0B"}
{"type":"response","@timestamp":"2018-01-25T19:15:55Z","tags":[],"pid":1125,"method":"get","statusCode":200,"req":{"url":"/bundles/commons.bundle.js?v=15523","method":"get","headers":{"host":"host-index","connection":"keep-alive","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 OPR/50.0.2762.58","accept":"*/*","referer":"http://host-index/app/kibana","accept-encoding":"gzip, deflate","accept-language":"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7"},"remoteAddress":"217.133.19.16","userAgent":"217.133.19.16","referer":"http://host-index/app/kibana"},"res":{"statusCode":200,"responseTime":532,"contentLength":9},"message":"GET /bundles/commons.bundle.js?v=15523 200 532ms - 9.0B"}
{"type":"log","@timestamp":"2018-01-25T19:15:56Z","tags":["status","info","Sentinl","scheduler"],"pid":1125,"message":"Executing watcher: svpa9s93ggh-j3c029abuvc-q6819vfnt5"}
{"type":"log","@timestamp":"2018-01-25T19:15:56Z","tags":["status","info","Sentinl","watcher"],"pid":1125,"message":"Executing action: svpa9s93ggh-j3c029abuvc-q6819vfnt5"}

```
where I've just replaced real host url with "host-index"

**Comment by sergibondarenko** [comment]
@matteobaire what are your Kibana and Elasticsearch versions?

**Comment by lmangani** [comment]
@matteobaire you can delete the watcher from the ES API using curl XDELETE at `${kibana_url}/api/sentinl/alarm/${index}/${type}/${id}` or just drop the SENTINL indices entirely if this was just a test and you have no critical Alerts ongoing, on restart SENTINL will re-create them from scratch.

**Comment by matteobaire** [comment]
@sergibondarenko 
I'm using version 5.6.6 for both Kibana and Elasticsearch

@lmangani 
Ok, thank you. I think I've solved.
