### ISSUE TITLE
Report with Search-guard

### ISSUE THREAD

**Issue by Ekouyoja** [sirensolutions/sentinl#343]
Hi,

Sentinl v: 6.2.2
Kibana v: 6.2.2
ES v: 6.2.2

I try to use the report function with my Search-guard but i experiment some problem, one due to SG and other one due to Sentinl himself.

The first one with SG is when i run my report task he can't go to my dashboard link because of SG credentials. When i check the log it's apparently OK. I have try with account that have all access like admin.
This is the report that sentinl return :
https://ibb.co/bGH0sx

I will report the second one in another issue.

**Comment by lmangani** [comment]
Could you confirm you followed the documentation for using SearchGuard: http://sentinl.readthedocs.io/en/latest/HOWTO-Sentinl-and-SearchGuard/

**Comment by Ekouyoja** [comment]
I didn't follow this documentation but I give to sentinl an Admin access. By the way it may work because I give all possible access to test this feature.

**Comment by lmangani** [comment]
I suggest to follow the documentation or we won't be able to assist much. Thanks!

**Comment by sergibondarenko** [comment]
@Ekouyoja also look this guide if you use basic auth in SearchGuard http://sentinl.readthedocs.io/en/latest/Authentication/#authenticate-search-request

**Comment by Ekouyoja** [comment]
Yes i use it and I have parameter there directive.
I have access on my server only Monday now. I will test to follow exactly the documentation but I think this is not rights problem.

**Comment by Ekouyoja** [comment]
I have try the exact config described in documentation and here is my error :
```
  log   [15:37:44.286] [error][Sentinl][action] fail to report, Error: Failed to GET url: http://www.google.com
  log   [15:37:44.287] [debug][Sentinl][log_history] storing alarm to Elasticsearch, action: New report action pszei5xvb7
 error  [15:37:44.328] [error][Sentinl][log_history] [mapper_parsing_exception] failed to parse [message] :: {"path":"/watcher_alarms-2018.03.19/sentinl-alarm","query":{},"body":"{\"@timestamp\":\"2018-03-19T15:37:44.287Z\",\"watcher\":\"reporter_title\",\"level\":\"INFO\",\"message\":{},\"action\":\"New report action pszei5xvb7\",\"payload\":{},\"report\":false}","statusCode":400,"response":"{\"error\":{\"root_cause\":[{\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse [message]\"}],\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse [message]\",\"caused_by\":{\"type\":\"illegal_state_exception\",\"reason\":\"Can't get text on a START_OBJECT at 1:94\"}},\"status\":400}"}
    at respond (/usr/share/kibana/plugins/sentinl/node_modules/elasticsearch/src/lib/transport.js:307:15)
    at checkRespForFailure (/usr/share/kibana/plugins/sentinl/node_modules/elasticsearch/src/lib/transport.js:266:7)
    at HttpConnector.<anonymous> (/usr/share/kibana/plugins/sentinl/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
    at IncomingMessage.bound (/usr/share/kibana/plugins/sentinl/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
 error  [15:37:44.339] [warning][process] Error: fail to store alarm reporter_title, action New report action pszei5xvb7
    at /usr/share/kibana/plugins/sentinl/server/lib/log_history.js:51:11
    at throw (native)
    at step (/usr/share/kibana/plugins/sentinl/server/lib/log_history.js:66:191)
    at /usr/share/kibana/plugins/sentinl/server/lib/log_history.js:66:402
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

In this case I try to report google.fr but I have the same error when I try to access Dashboard on my Kibana

**Comment by Ekouyoja** [comment]
Mhhh I am not sure about it. I think I have upgrade before the installation of Sentinl.

Here the mapping of watcher_alarms

```
{
  "watcher_alarms": {
    "mappings": {
      "sentinl-alarm": {
        "properties": {
          "attachment": {
            "type": "binary"
          },
          "payload": {
            "type": "object",
            "dynamic": "true"
          }
        }
      }
    }
  }
}
```

And here the mapping of watcher_alarms-2018.03.20

```
{
  "watcher_alarms-2018.03.20": {
    "mappings": {
      "sentinl-alarm": {
        "properties": {
          "@timestamp": {
            "type": "date"
          },
          "action": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "level": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "message": {
            "type": "object"
          },
          "payload": {
            "type": "object"
          },
          "report": {
            "type": "boolean"
          },
          "watcher": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          }
        }
      }
    }
  }
}
```

I have remove all watcher index and restart before give you mapping indices.

**Comment by lmangani** [comment]
Error  "Can't get text on a START_OBJECT" indicates Elasticsearch was expecting an entry of type "string" but you are trying to give an object as input. @sergibondarenko does this suggest a root cause to you?
