### ISSUE TITLE
Error second execution of report

### ISSUE THREAD

**Issue by Ekouyoja** [sirensolutions/sentinl#344]
Hi,

Sentinl v: 6.2.2
Kibana v: 6.2.2
ES v: 6.2.2

Here is my second problem.
It appears when I execute for the second time my report.
When i reboot my kibana service the first execution of my report task run without error but the second time appear some errors. Here the logs of Kibana.
```
Mar 13 15:55:41 racdata-test kibana: {"type":"error","@timestamp":"2018-03-13T14:55:41Z","tags":["error","Sentinl","log_history"],"pid":103246,"level":"error","error":{"message":"[mapper_parsing_exception] object mapping for [message] tried to parse field [message] as object, but found a concrete value","name":"Error","stack":"[mapper_parsing_exception] object mapping for [message] tried to parse field [message] as object, but found a concrete value :: {\"path\":\"/watcher_alarms-2018.03.13/sentinl-alarm\",\"query\":{},\"body\":\"{\\\"@timestamp\\\":\\\"2018-03-13T14:55:41.308Z\\\",\\\"watcher\\\":\\\"reporter_title\\\",\\\"level\\\":\\\"INFO\\\",\\\"message\\\":\\\"Action Throttled for 0h15m0s\\\",\\\"action\\\":\\\"report_admin\\\",\\\"payload\\\":{},\\\"report\\\":false}\",\"statusCode\":400,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"mapper_parsing_exception\\\",\\\"reason\\\":\\\"object mapping for [message] tried to parse field [message] as object, but found a concrete value\\\"}],\\\"type\\\":\\\"mapper_parsing_exception\\\",\\\"reason\\\":\\\"object mapping for [message] tried to parse field [message] as object, but found a concrete value\\\"},\\\"status\\\":400}\"}\n    at respond (/usr/share/kibana/plugins/sentinl/node_modules/elasticsearch/src/lib/transport.js:307:15)\n    at checkRespForFailure (/usr/share/kibana/plugins/sentinl/node_modules/elasticsearch/src/lib/transport.js:266:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/plugins/sentinl/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)\n    at IncomingMessage.bound (/usr/share/kibana/plugins/sentinl/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"},"message":"[mapper_parsing_exception] object mapping for [message] tried to parse field [message] as
Mar 13 15:55:41 racdata-test kibana: object, but found a concrete value"}
Mar 13 15:55:41 racdata-test kibana: {"type":"error","@timestamp":"2018-03-13T14:55:41Z","tags":["warning","process"],"pid":103246,"level":"error","error":{"message":"Unhandled promise rejection (rejection id: 2): Error: fail to store alarm reporter_title, action report_admin","name":"UnhandledPromiseRejectionWarning","stack":"Error: fail to store alarm reporter_title, action report_admin\n    at /usr/share/kibana/plugins/sentinl/server/lib/log_history.js:51:11\n    at throw (native)\n    at step (/usr/share/kibana/plugins/sentinl/server/lib/log_history.js:66:191)\n    at /usr/share/kibana/plugins/sentinl/server/lib/log_history.js:66:402\n    at process._tickDomainCallback (internal/process/next_tick.js:135:7)"},"message":"Unhandled promise rejection (rejection id: 2): Error: fail to store alarm reporter_title, action report_admin"}
```

**Comment by lmangani** [comment]
Hi,

The error is pointing at the message field:
```
"[mapper_parsing_exception] object mapping for [message] tried to parse field [message] as object, but found a concrete value"
```

In order to understand anything, you also need to paste the watcher you are executing please.

**Comment by lmangani** [comment]
On a second look this appears related to your other ticket [343](https://github.com/sirensolutions/sentinl/issues/343) due to authentication failure - let's follow the progress there and reopen this if needed afterwards. Thanks!
