### ISSUE TITLE
Sentinl + Searchguard Authentication Issue for reports generation

### ISSUE THREAD

**Issue by smhulkund** [sirensolutions/sentinl#407]
1. Sentinl  : 6.2.2 ( tag 6.2.3.2 ) {latest} 
    Kibana  : 6.2.2
    
2. Issue description
    Fail to authenticate via SearchGuard 
   
3. Reproducing the issue step-by-step

Browser(chrome) <--https---> Kibana <---http + basic auth via Searchguard --> Elasticsearch

    kibana.yml

###################### Kibana Configuration ################################
server.port: 5601
server.host: "10.10.10.10"
elasticsearch.url: "http://10.10.10.10:9200"
elasticsearch.username: _KUSR_
elasticsearch.password: _KPAS_

server.ssl.enabled: true
server.ssl.certificate: /etc/kibana/certs/kibana.crt
server.ssl.key: /etc/kibana/certs/kibana.key

elasticsearch.ssl.certificateAuthorities: [ "/etc/kibana/certs/root-ca.pem" ]
elasticsearch.ssl.verificationMode: none

######## Sentinl ########

sentinl:
  es:
    host: '10.10.10.10'
    port: 9200
    protocol: 'http'
  settings:
    authentication:
      enabled: true
      username: _KUSR_
      password: _KPAS_
    email:
      active: true
      host: '10.10.10.10'
    report:
      active: true
      executable_path: '/usr/bin/google-chrome'
      timeout: 5000
      authentication:
        enabled: true
        mode:
          searchguard: true

Searchguard config
A. sg_roles.yml

sg_kibana_server:
 ............
    'watcher*':
      '*':
       - indices:data/read/search
       - MANAGE
       - CREATE_INDEX
       - INDEX
       - READ
       - WRITE
       - DELETE
    '*':
      '*':
       - indices:data/read/search

B. sg_roles_mapping.yml

sg_kibana_server:
  readonly: true
  users:
  - "kibanaserver"
  hosts:
  - "10.10.10.10"
  - "10.10.10.11"

4. Ouput in Kibana ( debug mode )

[error][Sentinl][report_action] Error: fail to authenticate via Search Guard, user: admin, AssertionError: No node found for selector: #username
    at /usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:31:13
    at throw (native)
    at step (/usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:57:191)
    at /usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:57:402
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

I have tried various combinations, but no luck. How do i generate reports via searchguard authentication ?. 
If i don't set the authentication mode to searchguard, all i get is the screenshot of login page. this issue was reported earlier #193 .. is there any solution for non-kibi users ?

**Comment by sergibondarenko** [comment]
@smhulkund 
This part of the error message gives a clue: `AssertionError: No node found for selector: #username`. 

In case of Kibana+SearchGuard, the report (headless Chrome) [is looking for HTML selectors](https://github.com/sirensolutions/sentinl/blob/master/server/lib/actions/actions/report.js#L18) in order to type into username and password fields. Seems it doesn't find `#username` selector anymore. 

Do you have a customized Search Guard login page? 
Another possible thing, Search Guard has new selectors for these fields. Please check it in HTML source of the login page. Or just paste HTML source here and I'll look on it.

There is a possibility to specify [custom selectors for Sentinl report](http://sentinl.readthedocs.io/en/latest/Authentication/#kibana-configuration-for-sentinl-v6). Thus making report capable to login to any page:
```
sentinl:
  settings:
    report:
      active: true
      authentication:
        enabled: true
        mode:
          custom: true
        custom: # you have to replace the following selectors with selectors found on your login page
          username_input_selector: '#username'
          password_input_selector: '#password'
          login_btn_selector: '#login-btn'
```

**Comment by smhulkund** [comment]
Thank you @sergibondarenko,

Well here is the login page

```
<div class="container login-wrapper" style="">
<div class="text-center license-error"><sg-license-warning>
<div id="sg.label.licensehint" class="licensehint"></div></sg-license-warning></div>
 <p class="login-title" ng-show="ui.logintitle != ''">Kibana</p>
 <p class="login-subtitle" ng-show="ui.loginsubtitle != ''">Searchguard</p>
 <form class="login-form ng-pristine ng-invalid ng-invalid-required" ng-submit="ui.submit()" method="post" autocomplete="off">
<input autocomplete="anyrandomstring" name="hidden" type="text" style="display:none;">
<div class="input-group">
<div class="input-group-addon"><i class="fa fa-user"></i></div>
<input type="text" class="form-control kuiTextInput ng-pristine ng-empty ng-invalid ng-invalid-required ng-touched" id="sg.username" name="username" placeholder="Username" ng-class="{'has-error': ui.errorMessage}" ng-model="ui.credentials.username" required="" autofocus="" autocomplete="off">
    </div>
<div class="input-group">
<div class="input-group-addon"><i class="fa fa-lock"></i></div>
<input type="password" autocomplete="off" class="form-control kuiTextInput ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required" id="sg.password" name="password" placeholder="Password" ng-class="{'has-error': ui.errorMessage}" ng-model="ui.credentials.password" required="">
</div>
<button id="sg.login" type="submit" class="btn btn-default btn-login" ng-attr-style="{{ui.buttonstyle}}" style="">Log in</button>
  </form>
</div>

```
Is this correct ?

> username_input_selector: '#sg.username' 

or

> username_input_selector:  '#sg.username.form-control.kuiTextInput.ng-pristine.ng-empty.ng-invalid.ng-invalid-required.ng-touched' 


Either way, I get this error message

`Error: fail to authenticate via custom auth, user: elk, AssertionError: No node found for selector: #user
    at /usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:42:13
    at throw (native)
    at step (/usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:57:191)
    at /usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:57:402
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
`

**Comment by smhulkund** [comment]
@sergibondarenko  were you able to take a look ..

is it config error or a bug ?

**Comment by sergibondarenko** [comment]
@smhulkund It is a bug. The selector values are hardcoded here https://github.com/sirensolutions/sentinl/blob/master/server/lib/actions/actions/report.js#L106 I'll fix this.

**Comment by smhulkund** [comment]
Thank you, appreciate your help @sergibondarenko.

Well, can i know when will the fix be available.

**Comment by OleksandrSlobodian** [comment]
```
{"type":"error","@timestamp":"2018-05-03T21:40:02Z","tags":["error","Sentinl","report_action"],"pid":3752,"level":"error","error":{"message":"fail to authenticate via Search Guard, user: undefined, AssertionError: No node found for selector: #sg.username","name":"Error","stack":"Error: fail to authenticate via Search Guard, user: undefined, AssertionError: No node found for selector: #sg.username\n    at /usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:32:13\n    at throw (native)\n    at step (/usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:57:191)\n    at /usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:57:402\n    at process._tickDomainCallback (internal/process/next_tick.js:135:7)"},"message":"fail to authenticate via Search Guard, user: undefined, AssertionError: No node found for selector: #sg.username"}
```

Interesting why user: undefined

**Comment by OleksandrSlobodian** [comment]
```
await page.type('input[type="text"]', user, {delay: timeout / 50});
      await page.type('input[type="password"]', pass, {delay: timeout / 50});

      if (appName === 'xpack') {
        await page.click('.kuiButton');
      } else {
        await page.click('button[type="submit"]');
      }
```
this fixed my auth issues for searchguard

**Comment by smhulkund** [comment]
Thanks @OleksandrSlobodian.

Well I fixed my auth problem by changing the values of login screen in searchguard

From 

> <input type="text" class="form-control kuiTextInput" id="sg.username" name="username" ....
> <input type="password" autocomplete="off" class="form-control kuiTextInput" id="sg.password" name="password" ....
> <button id="sg.login" type="submit" class="btn btn-default btn-login"  .....

To

> <input type="text" class="form-control kuiTextInput" id="username" name="username" .....
> <input type="password" autocomplete="off" class="form-control kuiTextInput" id="password" name="password" ....
> <button id=".btn-login" type="submit" class="btn btn-default btn-login"  .....

However, the problem of report generation for embed-ed dashboard exists .. 

```
[error][Sentinl][report_action] Error: fail to authenticate via Search Guard, user: reports, Error: Node is either not visible or not an HTMLElement
    at /usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:31:13
    at throw (native)
    at step (/usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:57:191)
    at /usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:57:402
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

```
@sergibondarenko do i raise it as a new issue ?

**Comment by sergibondarenko** [comment]
@smhulkund the error message means you use a wrong CSS selector to find DOM element. In Chrome dev tools you can check if your selector works https://developers.google.com/web/updates/2015/05/search-dom-tree-by-css-selector

**Comment by sergibondarenko** [comment]
Try [the latest release](https://github.com/sirensolutions/sentinl/releases/tag/tag-6.2.3-3) where the bug related to the report custom authentication was fixed. But you have to put correct CSS selectors anyway.

**Comment by smhulkund** [comment]
Thank you @sergibondarenko, I changed the CSS selector and now its working, you can close this request.

The Sentinl config in kibana.yml is ..

```
######## Sentinl ########

sentinl:
  es:
    host: '10.10.10.10'
    port: 9200
  settings:
    authentication:
      enabled: true
      username: _KUSR_ 
      password: _KPAS_ 
    email:
      active: true
      host: '10.10.10.10'
    report:
      active: true
      executable_path: '/usr/bin/google-chrome' 
      timeout: 5000
      authentication:
        enabled: true
        mode:
          custom: true
        custom:
          username_input_selector: '#sg\.username'
          password_input_selector: '#sg\.password'
          login_btn_selector: '#sg\.login'

```

You could link this solved issue to faqs section.
