### ISSUE TITLE
Basic auth for Report action fails with js error

### ISSUE THREAD

**Issue by brandonwestcott** [sirensolutions/sentinl#414]
1. Sentinl and Kibana version 
Sentinl version: 6.2.3-1
Kibana version: 6.1.1

2. Issue description
I can not seem to get basic authentication for report generation to work - configuration below produces a js error:

3. Reproducing the issue step-by-step
**kibana.yml**
```yaml
sentinl:
  settings:
    authentication:
      enabled: true
      username: 'kibanaserver'
      password: 'kibanaserver'
    report:
      active: true
      executable_path: '/usr/bin/chrome'
      authentication:
        enabled: true
        mode:
          basic: true
```

**watcher configuration:**
```
{
  "actions": {
    "report_admin": {
      "throttle_period": "0h0m0s",
      "report": {
        "to": "localhost",
        "from": "localhost",
        "subject": "My Report",
        "priority": "high",
        "body": "Sample Screenshot Report",
        "save": true,
        "snapshot": {
          "res": "1300x700",
          "url": "https://localhost:5601/app/kibana#/dashboard/dbfc49a0-4d65-11e8-b831-73cc26a60099?embed=true&_g=()",
          "params": {
            "delay": 3000,
            "crop": "false"
          },
          "type": "png",
          "name": "somereport"
        }
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [],
        "body": {}
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total >= 0"
    }
  },
  "transform": {},
  "trigger": {
    "schedule": {
      "later": "every 5 minutes"
    }
  },
  "disable": false,
  "report": true,
  "title": "reporter_title"
}
```

4. Expected results vs. actual results

Expected result is for basic auth header to get set with correct credentials before opening a page inside of the headless browser. 

Actual result is
```
{
  "type": "error",
  "@timestamp": "2018-05-02T13:00:47Z",
  "tags": [
    "error",
    "Sentinl",
    "report_action"
  ],
  "pid": 1,
  "level": "error",
  "error": {
    "message": "Cannot read property 'username' of undefined",
    "name": "TypeError",
    "stack": "TypeError: Cannot read property 'username' of undefined\n    at /usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:79:56\n    at next (native)\n    at step (/usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:57:191)\n    at /usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:57:361\n    at process._tickDomainCallback (internal/process/next_tick.js:135:7)"
  },
  "message": "Cannot read property 'username' of undefined"
}
```

5. Additional details
I believe this is a bug on https://github.com/sirensolutions/sentinl/blob/master/server/lib/actions/actions/report.js#L79 -  it does not appear to me that `this.authentication` is being defined. I believe that either needs to be injected into the `Report` object from `getConfiguration(server).settings.authentication`, or could also be defined and pulled from `this.config.authentication.(username|password)`. If this is indeed a bug, I'm more than happy to open a PR with either of those changes.

**Comment by sergibondarenko** [comment]
@brandonwestcott I don't see username and password fields in your watcher action config.
Should be like this
```
      "report": {
        "snapshot": {
          "params": {
            "username": "kibiadmin",
            "password": "password"
```

**Comment by brandonwestcott** [comment]
@sergibondarenko I've added that to the watcher, however, I still get the same error. I see those params above being set [here]( https://github.com/sirensolutions/sentinl/blob/master/server/lib/actions/actions/report.js#L214-L215), but I think the cause of the error is still that [this code](https://github.com/sirensolutions/sentinl/blob/master/server/lib/actions/actions/report.js#L79) is using `this.authentication` instead of `this.config.authentication`. 


New watcher config:
```
{
  "actions": {
    "report_admin": {
      "throttle_period": "0h0m0s",
      "report": {
        "to": "localhost",
        "from": "localhost",
        "subject": "My Report",
        "priority": "high",
        "body": "Sample Screenshot Report",
        "save": true,
        "snapshot": {
          "res": "1300x700",
          "url": "https://localhost:5601/app/kibana#/dashboard/dbfc49a0-4d65-11e8-b831-73cc26a60099?embed=true&_g=()",
          "params": {
            "delay": 3000,
            "crop": "false",
            "username": "kibanaserver",
            "password": "kibanaserver"
          },
          "type": "png",
          "name": "somereport"
        }
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [],
        "body": {}
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total >= 0"
    }
  },
  "transform": {},
  "trigger": {
    "schedule": {
      "later": "every 5 minutes"
    }
  },
  "disable": false,
  "report": true,
  "title": "reporter_title"
}
```

Error:
```
{
  "type": "error",
  "@timestamp": "2018-05-04T17:39:14Z",
  "tags": [
    "error",
    "Sentinl",
    "report_action"
  ],
  "pid": 1,
  "level": "error",
  "error": {
    "message": "Cannot read property 'username' of undefined",
    "name": "TypeError",
    "stack": "TypeError: Cannot read property 'username' of undefined\n    at /usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:79:56\n    at next (native)\n    at step (/usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:57:191)\n    at /usr/share/kibana/plugins/sentinl/server/lib/actions/actions/report.js:57:361\n    at process._tickDomainCallback (internal/process/next_tick.js:135:7)"
  },
  "message": "Cannot read property 'username' of undefined"
}
```

**Comment by sergibondarenko** [comment]
@brandonwestcott please check the latest release, there are some important fixes related to report https://github.com/sirensolutions/sentinl/releases/tag/tag-6.2.3-3

Also, look at this doc and verify the report authentication config https://github.com/sirensolutions/sentinl/blob/master/docs/Authentication.md#kibana-configuration-for-sentinl-v6

**Comment by sergibondarenko** [comment]
Please reopen this issue if you still have problems.

**Comment by brandonwestcott** [comment]
@sergibondarenko even after updating the issue still persists, I've opened [this PR](https://github.com/sirensolutions/sentinl/pull/427) to fix what I believe is the underlying bug.
