### ISSUE TITLE
'RCPT': 5.1.3 Bad recipient address syntax

### ISSUE THREAD

**Issue by manish2479** [sirensolutions/sentinl#430]
Hi 

Somehow kibana process stopped and then when I try to restart the kibana service I am getting error as bad recipient address so how I can fix that error.

Kibana v 6.2.2
sentinl v sentinl@6.0.0

```
{ Error: bad response on command 'RCPT': 5.1.3 Bad recipient address syntax
    at module.exports (/usr/share/kibana/plugins/sentinl/node_modules/emailjs/smtp/error.js:3:13)
    at response (/usr/share/kibana/plugins/sentinl/node_modules/emailjs/smtp/smtp.js:207:28)
    at caller (/usr/share/kibana/plugins/sentinl/node_modules/emailjs/smtp/smtp.js:48:14)
    at Socket.response (/usr/share/kibana/plugins/sentinl/node_modules/emailjs/smtp/smtp.js:181:11)
    at Socket.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at notify (/usr/share/kibana/plugins/sentinl/node_modules/emailjs/smtp/response.js:19:14)
    at Socket.watch (/usr/share/kibana/plugins/sentinl/node_modules/emailjs/smtp/response.js:44:7)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20) code: 2, smtp: '501 5.1.3 Bad recipient address syntax\n' }
chroot: invalid user
FATAL "sentinl.settings.email.active", "sentinl.settings.email.user", "sentinl.settings.email.host", "sentinl.settings.email.ssl", and "sentinl.settings.report.active" settings were not applied. Check for spelling errors and ensure that expected plugins are installed and enabled.
```

Thank You

**Comment by lmangani** [comment]
What's the format of the TO address you configured? According to the error message, that's the culprit

**Comment by manish2479** [comment]
Hi 

Thanks for the prompt response, yes that's what I thought but I am not sure which email address that could be and as I can't get the web portal running I can't check which one is that culprit. 

Is there a way using cli I can check that configuration. Where that configurations would be saved and how I can list and modify it using command line.

Thank You

**Comment by lmangani** [comment]
Closing as this doesn't appear to be a bug or feature request. Feel free to continue commenting if you need help/advice.

**Comment by manish2479** [comment]
Hi,

I agree it's bad email address, but where does those configurations are saved in Elasticsearch kibana DB or it's using some other file which can be edited using vi or any other editor. As thw kibana Web portal is not loading as I can't start Kibana Services due to that error.

Thank you
