### ISSUE TITLE
Impersonation/Security: fail to execute watcher with fail to impersonate Elasticsearch API client: fail to authenticate watcher, user was not found

### ISSUE THREAD

**Issue by havlan** [sirensolutions/sentinl#491]
1. Sentinl and Kibana version 
Kibana: 6.2.4
ES: 6.2.4
Sentinl: 6.2.4
Searchguard: 6.2.4-31.2 (TRIAL)

2. Issue description
With a working Searchguard configuration I am unable to authenticate watchers/find them. And at the same time confused on how it's supposed to work.

I've added this to the kibana.yml.

My confusion and question is, what does this user do? I know I can authenticate each watcher, but how does it actually do that? Do I need to manually create users for each watcher? Does the creation of users happen automatically? If so, then every user who creates watchers would need admin access?

```json
  settings:
    authentication:
      enabled: true
      impersonate: true
      username: 'sentinl'
      password: 'some_pw'
      cert:
        selfsigned: true
```

When creating a watcher, what is the username and password to pass along with the watcher? Is it for the user its going to impersonate? Is it for the watcher itself? And what is the function of adding config of a user in the kibana.yml config file?

Error: ```Watchers: fail to execute watcher: fail to impersonate Elasticsearch API client: fail to authenticate watcher, user was not found. ```

```json
juli 04 09:55:39 localhost:5601 kibana[7031]: {"type":"log","@timestamp":"2018-07-04T07:55:39Z","tags":["warning","Sentinl","watcher a1e15450-7ea6-11e8-a1b4-1d2ba29f02e1"],"pid":7031,"message":"\"elasticsearch.plugins\" not available when running from kibana"}
juli 04 09:55:39 localhost kibana[7031]: {"type":"log","@timestamp":"2018-07-04T07:55:39Z","tags":["error","Sentinl","watcher a1e15450-7ea6-11e8-a1b4-1d2ba29f02e1"],"pid":7031,"message":"fail to impersonate Elasticsearch API client: fail to authenticate watcher, user was not found: fail to authenticate watcher, user was not found"}
juli 04 09:55:39 localhost kibana[7031]: {"type":"log","@timestamp":"2018-07-04T07:55:39Z","tags":["error","Sentinl","watcher a1e15450-7ea6-11e8-a1b4-1d2ba29f02e1"],"pid":7031,"message":"fail to execute watcher: fail to impersonate Elasticsearch API client: fail to authenticate watcher, user was not found: fail to impersonate Elasticsearch API client: fail to authenticate watcher, user was not found"}
juli 04 09:55:39 localhost kibana[7031]: {"type":"response","@timestamp":"2018-07-04T07:55:39Z","tags":[],"pid":7031,"method":"post","statusCode":406,"req":{"url":"/api/sentinl/watcher/_execute","method":"post","headers":{"host":"localhost:5601","connection":"keep-alive","content-length":"1134","accept":"application/json, text/plain, */*","origin":"https://localhost:5601","kbn-version":"6.2.4","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/66.0.3359.181 Chrome/66.0.3359.181 Safari/537.36","content-type":"application/json;charset=UTF-8","referer":"https://localhost:5601/app/sentinl","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","sgtenant":"admin_tenant"},"remoteAddress":"158.38.63.16","userAgent":"158.38.63.16","referer":"https://localhost:5601/app/sentinl"},"res":{"statusCode":406,"responseTime":33,"contentLength":9},"message":"POST /api/sentinl/watcher/_execute 406 33ms - 9.0B"}
juli 04 09:55:39 localhost kibana[7031]: {"type":"log","@timestamp":"2018-07-04T07:55:39Z","tags":["error","Sentinl","watcher a1e15450-7ea6-11e8-a1b4-1d2ba29f02e1"],"pid":7031,"message":"fail to get user: Not Found: {\"msg\":\"Not Found\",\"path\":\"/.kibana/doc/a1e15450-7ea6-11e8-a1b4-1d2ba29f02e1\",\"query\":{},\"statusCode\":404,\"response\":\"{\\\"_index\\\":\\\".kibana\\\",\\\"_type\\\":\\\"doc\\\",\\\"_id\\\":\\\"a1e15450-7ea6-11e8-a1b4-1d2ba29f02e1\\\",\\\"found\\\":false}\"}"}
juli 04 09:55:39 localhost kibana[7031]: Unhandled rejection Error: fail to get user: Not Found
juli 04 09:55:39 localhost kibana[7031]:     at /usr/share/kibana/plugins/sentinl/server/lib/watcher_handler.js:70:13
juli 04 09:55:39 localhost kibana[7031]:     at throw (native)
juli 04 09:55:39 localhost kibana[7031]:     at step (/usr/share/kibana/plugins/sentinl/server/lib/watcher_handler.js:61:202)
juli 04 09:55:39 localhost kibana[7031]:     at /usr/share/kibana/plugins/sentinl/server/lib/watcher_handler.js:61:424
juli 04 09:55:39 localhost kibana[7031]:     at tryCatcher (/usr/share/kibana/plugins/sentinl/node_modules/bluebird/js/release/util.js:16:23)
juli 04 09:55:39 localhost kibana[7031]:     at Promise._settlePromiseFromHandler (/usr/share/kibana/plugins/sentinl/node_modules/bluebird/js/release/promise.js:510:31)
juli 04 09:55:39 localhost kibana[7031]:     at Promise._settlePromise (/usr/share/kibana/plugins/sentinl/node_modules/bluebird/js/release/promise.js:567:18)
juli 04 09:55:39 localhost kibana[7031]:     at Promise._settlePromise0 (/usr/share/kibana/plugins/sentinl/node_modules/bluebird/js/release/promise.js:612:10)
juli 04 09:55:39 localhost kibana[7031]:     at Promise._settlePromises (/usr/share/kibana/plugins/sentinl/node_modules/bluebird/js/release/promise.js:687:18)
juli 04 09:55:39 localhost kibana[7031]:     at Async._drainQueue (/usr/share/kibana/plugins/sentinl/node_modules/bluebird/js/release/async.js:133:16)
juli 04 09:55:39 localhost kibana[7031]:     at Async._drainQueues (/usr/share/kibana/plugins/sentinl/node_modules/bluebird/js/release/async.js:143:10)
juli 04 09:55:39 localhost kibana[7031]:     at Immediate.Async.drainQueues (/usr/share/kibana/plugins/sentinl/node_modules/bluebird/js/release/async.js:17:14)
juli 04 09:55:39 localhost kibana[7031]:     at runCallback (timers.js:672:20)
juli 04 09:55:39 localhost kibana[7031]:     at tryOnImmediate (timers.js:645:5)
juli 04 09:55:39 localhost kibana[7031]:     at processImmediate [as _immediateCallback] (timers.js:617:5)
juli 04 09:55:40 localhost kibana[7031]: {"type":"ops","@timestamp":"2018-07-04T07:55:40Z","tags":[],"pid":7031,"os":{"load":[0,0,0],"mem":{"total":8374988800,"free":1321816064},"uptime":3618733},"proc":{"uptime":1331.995,"mem":{"rss":164446208,"heapTotal":107458560,"heapUsed":90908592,"external":543414},"delay":0.4487342834472656},"load":{"requests":{"5601":{"total":2,"disconnects":0,"statusCodes":{"200":1,"406":1}}},"concurrents":{"5601":1},"responseTimes":{"5601":{"avg":50.5,"max":68}},"sockets":{"http":{"total":0},"https":{"total":0}}},"message":"memory: 86.7MB uptime: 0:22:12 load: [0.00 0.00 0.00] delay: 0.449"}
```

Also an issue/bug that occurs unrelated to the issue above, when using Multitenancy (separate .kibana index), I am able to manually execute watchers on watchers that are located on separate .kibana indices, but the scheduler does not pick them up for execution. If desirable I will open another issue with detailed information. 

3. Reproducing the issue step-by-step
With impersonation enabled and searchguard working.
Create a new watcher.
Random username and password leads to error.
Kibana.yml username and password leads to error.

4. Expected results vs. actual results
I expect the kibana.yml config user to run all queries for watchers.
I expect it to happen somewhat automatically.

5. Sample of data

6. Additional details
If I get enough to work with, I will update the documentation with a PR.

**Comment by havlan** [comment]
Found out that when saving to .kibana, it added ```sentinl-user:``` before the id.
This hits.
```json
GET .kibana/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "_id": "sentinl-user:b9d630e0-8373-11e8-b948-01a0ca845ebe"
          }
        }
      ]
    }
  }
}
```

And this does not.
```json
GET .kibana/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "_id": "b9d630e0-8373-11e8-b948-01a0ca845ebe"
          }
        }
      ]
    }
  }
}
```

**Comment by sergibondarenko** [comment]
The issue was fixed, get the latest zip https://github.com/sirensolutions/sentinl/releases/tag/tag-6.2.3-3
Look the doc for config details https://github.com/sirensolutions/sentinl/blob/master/docs/Authentication.md
Reopen the issue if you still have problems.
