### ISSUE TITLE
Sentinl attempts to modify its own code

### ISSUE THREAD

**Issue by andrewgdotcom** [sirensolutions/sentinl#510]
On startup, sentinl attempts to modify `public/app.js`, which is a file under the code tree. This is bad practice, as it prevents proper privilege separation.

If code needs to be modified at runtime, the changes should be performed on a copy stored outside the code tree, e.g. in `../../optimize`.

```
Jul 24 08:57:25 xxxxxxxx.siren.solutions investigate[28962]: {"type":"error","@timestamp":"2018-07-24T08:57:25Z","tags":["fatal"],"pid":28962,"level":"fatal","error":{"message":"put libs into app.js: EACCES: permission denied, open '/opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/siren_plugins/sentinl/public/app.js'","name":"Error","stack":"Error: put libs into app.js: EACCES: permission denied, open '/opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/siren_plugins/sentinl/public/app.js'\n    at exports.default (/opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/siren_plugins/sentinl/index.js:58:11)\n    at /opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/src/server/plugins/plugin_collection.js:79:45\n    at next (native)\n    at step (/opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/src/server/plugins/plugin_collection.js:49:191)\n    at /opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/src/server/plugins/plugin_collection.js:49:437\n    at /opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/src/server/plugins/plugin_collection.js:49:99\n    at Plugins.new (/opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/src/server/plugins/plugin_collection.js:115:7)\n    at KbnServer.<anonymous> (/opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/src/server/plugins/scan.js:94:26)\n    at next (native)\n    at step (/opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/src/server/plugins/scan.js:19:191)\n    at /opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/src/server/plugins/scan.js:19:361"},"message":"put libs into app.js: EACCES: permission denied, open '/opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/siren_plugins/sentinl/public/app.js'"}
Jul 24 08:57:25 xxxxxxxx.siren.solutions investigate[28962]: FATAL Error: put libs into app.js: EACCES: permission denied, open '/opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/siren_plugins/sentinl/public/app.js'
Jul 24 08:57:25 xxxxxxxx.siren.solutions investigate[28962]:     at exports.default (/opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/siren_plugins/sentinl/index.js:58:11)
Jul 24 08:57:25 xxxxxxxx.siren.solutions investigate[28962]:     at /opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/src/server/plugins/plugin_collection.js:79:45
Jul 24 08:57:25 xxxxxxxx.siren.solutions investigate[28962]:     at next (native)
Jul 24 08:57:25 xxxxxxxx.siren.solutions investigate[28962]:     at step (/opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/src/server/plugins/plugin_collection.js:49:191)
Jul 24 08:57:25 xxxxxxxx.siren.solutions investigate[28962]:     at /opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/src/server/plugins/plugin_collection.js:49:437
Jul 24 08:57:25 xxxxxxxx.siren.solutions investigate[28962]:     at /opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/src/server/plugins/plugin_collection.js:49:99
Jul 24 08:57:25 xxxxxxxx.siren.solutions investigate[28962]:     at Plugins.new (/opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/src/server/plugins/plugin_collection.js:115:7)
Jul 24 08:57:25 xxxxxxxx.siren.solutions investigate[28962]:     at KbnServer.<anonymous> (/opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/src/server/plugins/scan.js:94:26)
Jul 24 08:57:25 xxxxxxxx.siren.solutions investigate[28962]:     at next (native)
Jul 24 08:57:25 xxxxxxxx.siren.solutions investigate[28962]:     at step (/opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/src/server/plugins/scan.js:19:191)
Jul 24 08:57:25 xxxxxxxx.siren.solutions investigate[28962]:     at /opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/src/server/plugins/scan.js:19:361
```

**Comment by andrewgdotcom** [comment]
Two more offending files:

```
Jul 24 09:16:04 xxxxxxxx.siren.solutions investigate[30856]: FATAL { Error: EPERM: operation not permitted, chmod '/opt/test101.kibisiem/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/siren_plugins/sentinl/node_modules/phantomjs-prebuilt/bin/phantomjs'
Jul 24 09:17:42 xxxxxxxx.siren.solutions investigate[32296]: [sentinl] fail to make report engine executable: EPERM: operation not permitted, chmod '/opt/test101.xxxxxxxx/siren-investigate-10.1.0-SNAPSHOT-linux-x86_64/siren_plugins/sentinl/node_modules/puppeteer/.local-chromium/linux-564778/chrome-linux/chrome'!
```

**Comment by sergibondarenko** [comment]
@andrewgdotcom 
Siren creates issues here https://github.com/sirensolutions/sentinl-private

This app.js change is needed to import correct SavedObjectsAPI objects:
```
if Siren:
  import Siren SavedObjectsAPI
else: 
  import Kibana SavedObjectsAPI
```
I remember I tried to require modules conditionally but it didn't work. I'll try again but now we have more urgent issues.

**Comment by andrewgdotcom** [comment]
Issue moved to [sirensolutions/sentinl-private #679](https://github.com/sirensolutions/sentinl-private/issues/679) via [**ZenHub**](https://www.zenhub.com/)
