### ISSUE TITLE
child \"sentinl\" fails on kibana start

### ISSUE THREAD

**Issue by duoonp** [sirensolutions/sentinl#540]
1. Sentinl and Kibana version

`releases/download/tag-6.2.4/sentinl-v6.2.4.zip`
version: '6.2.4',
branch: '6.x',
buildNum: 16627

`kibana-oss:6.2.4`

2. Issue description
Keys `hook`, `channel`, `username` in `sentinl.settings.slack` are displayed in logs as not allowed.
Key `active` is OK
3. Reproducing the issue step-by-step
```
   sentinl:
      settings:
        slack:
          active: true
          username: sentinl
          hook: 'https://hooks.slack.com/services/...'
          channel: '#alerts'
```
4. Expected results vs. actual results
Results:
Kibana doesn't start with `ValidationError`
5. Sample of data
```
➜  ~ kubectl logs kibana-7lgsm
{"type":"error","@timestamp":"2018-09-19T09:21:22Z","tags":["fatal"],"pid":1,"level":"fatal","error":{"message":"child \"sentinl\" fails because [child \"settings\" fails because [child \"slack\" fails because [\"username\" is not allowed, \"hook\" is not allowed, \"channel\" is not allowed]]]","name":"ValidationError","stack":"ValidationError: child \"sentinl\" fails because [child \"settings\" fails because [child \"slack\" fails because [\"username\" is not allowed, \"hook\" is not allowed, \"channel\" is not allowed]]]\n    at Object.exports.process (/usr/share/kibana/node_modules/joi/lib/errors.js:181:19)\n    at _validateWithOptions (/usr/share/kibana/node_modules/joi/lib/any.js:651:31)\n    at root.validate (/usr/share/kibana/node_modules/joi/lib/index.js:121:23)\n    at Config._commit (/usr/share/kibana/src/server/config/config.js:119:35)\n    at Config.set (/usr/share/kibana/src/server/config/config.js:89:10)\n    at Config.extendSchema (/usr/share/kibana/src/server/config/config.js:62:10)\n    at /usr/share/kibana/src/plugin_discovery/plugin_config/extend_config_service.js:22:12\n    at next (native)\n    at step (/usr/share/kibana/src/plugin_discovery/plugin_config/extend_config_service.js:45:191)\n    at /usr/share/kibana/src/plugin_discovery/plugin_config/extend_config_service.js:45:361"},"message":"child \"sentinl\" fails because [child \"settings\" fails because [child \"slack\" fails because [\"username\" is not allowed, \"hook\" is not allowed, \"channel\" is not allowed]]]"}
FATAL { ValidationError: child "sentinl" fails because [child "settings" fails because [child "slack" fails because ["username" is not allowed, "hook" is not allowed, "channel" is not allowed]]]
    at Object.exports.process (/usr/share/kibana/node_modules/joi/lib/errors.js:181:19)
    at _validateWithOptions (/usr/share/kibana/node_modules/joi/lib/any.js:651:31)
    at root.validate (/usr/share/kibana/node_modules/joi/lib/index.js:121:23)
    at Config._commit (/usr/share/kibana/src/server/config/config.js:119:35)
    at Config.set (/usr/share/kibana/src/server/config/config.js:89:10)
    at Config.extendSchema (/usr/share/kibana/src/server/config/config.js:62:10)
    at /usr/share/kibana/src/plugin_discovery/plugin_config/extend_config_service.js:22:12
    at next (native)
    at step (/usr/share/kibana/src/plugin_discovery/plugin_config/extend_config_service.js:45:191)
    at /usr/share/kibana/src/plugin_discovery/plugin_config/extend_config_service.js:45:361
  isJoi: true,
  name: 'ValidationError',
  details:
   [ { message: '"username" is not allowed',
       path: 'sentinl.settings.slack.username',
       type: 'object.allowUnknown',
       context: [Object] },
     { message: '"hook" is not allowed',
       path: 'sentinl.settings.slack.hook',
       type: 'object.allowUnknown',
       context: [Object] },
     { message: '"channel" is not allowed',
       path: 'sentinl.settings.slack.channel',
       type: 'object.allowUnknown',
       context: [Object] } ],
```
6. Additional details
Those options look like allowed in the `index.js`
https://github.com/sirensolutions/sentinl/blob/branch-6.2.x/index.js#L224

**Comment by sergibondarenko** [comment]
It is because we don't have those slack options anymore. The following options are available:
```
          slack:
            active: true,
            token: 2387882dj3kd3...,
```
Where `token` is from your Slack app or custom integration - xoxa, xoxp, or xoxb https://get.slack.help/hc/en-us/articles/215770388-Create-and-regenerate-API-tokens

**Comment by duoonp** [comment]
Thank you for explaining. Have I missed some docs articles about this options?
