### ISSUE TITLE
Install Sentinl on Kibana 6.4.0 fails

### ISSUE THREAD

**Issue by fbaligand** [sirensolutions/sentinl#558]
0.  OS
Windows 10
1. Sentinl and Kibana version 
Sentinl 6.4.X for Kibana 6.4.0

2. Issue description
When I install the plugin on Kibana 6.4.0, I get a blocking error

3. Error
Here is the logged error : 

```
{"type":"error","@timestamp":"2018-10-01T20:08:59Z","tags":["fatal"],"pid":20312,"level":"fatal","error":{"message":"Optimizations failure.\n   4395 modules\n    \n    \u001b[1m\u001b[31mERROR in ./plugins/sentinl/public/app.js\n    Module build failed: SyntaxError: C:/Developpement/outils/elk/kibana-6.4.0-windows-x86_64/plugins/sentinl/public/app.js: Bad character escape sequence (56:99)\n    \n      54 | import './C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\plugins\\sentinl\\public\\services\\sentinl_helper';\n      55 | import './C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\plugins\\sentinl\\public\\services\\sentinl_log';\n    > 56 | import './C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\plugins\\sentinl\\public\\services\\user_service';\n         |                                                                                                    ^\n      57 | import './C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\plugins\\sentinl\\public\\services\\watcher_service';\n      58 | import './C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\plugins\\sentinl\\public\\constants\\api.js';\n      59 | import './C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\plugins\\sentinl\\public\\constants\\common.js';\n    \u001b[39m\u001b[22m\n","name":"Error","stack":"Error: Optimizations failure.\n   4395 modules\n    \n    \u001b[1m\u001b[31mERROR in ./plugins/sentinl/public/app.js\n    Module build failed: SyntaxError: C:/Developpement/outils/elk/kibana-6.4.0-windows-x86_64/plugins/sentinl/public/app.js: Bad character escape sequence (56:99)\n    \n      54 | import './C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\plugins\\sentinl\\public\\services\\sentinl_helper';\n      55 | import './C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\plugins\\sentinl\\public\\services\\sentinl_log';\n    > 56 | import './C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\plugins\\sentinl\\public\\services\\user_service';\n         |                                                                                                    ^\n      57 | import './C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\plugins\\sentinl\\public\\services\\watcher_service';\n      58 | import './C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\plugins\\sentinl\\public\\constants\\api.js';\n      59 | import './C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\plugins\\sentinl\\public\\constants\\common.js';\n    \u001b[39m\u001b[22m\n\n    at FsOptimizer.failedStatsToError (C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\src\\optimize\\base_optimizer.js:378:27)\n    at compiler.run (C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\src\\optimize\\fs_optimizer.js:47:26)\n    at onCompiled (C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\node_modules\\webpack\\lib\\Compiler.js:241:12)\n    at applyPluginsAsync.err (C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\node_modules\\webpack\\lib\\Compiler.js:514:14)\n    at next (C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:202:11)\n    at Compiler.<anonymous> (C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\node_modules\\webpack\\lib\\CachePlugin.js:78:5)\n    at Compiler.applyPluginsAsyncSeries (C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:206:13)\n    at compilation.seal.err (C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\node_modules\\webpack\\lib\\Compiler.js:511:11)\n    at Compilation.applyPluginsAsyncSeries (C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:195:46)\n    at self.applyPluginsAsync.err (C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\node_modules\\webpack\\lib\\Compilation.js:671:19)\n    at Compilation.applyPluginsAsyncSeries (C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:195:46)\n    at self.applyPluginsAsync.err (C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\node_modules\\webpack\\lib\\Compilation.js:662:11)\n    at next (C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:202:11)\n    at C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\node_modules\\uglifyjs-webpack-plugin\\dist\\index.js:282:11\n    at step (C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\node_modules\\uglifyjs-webpack-plugin\\dist\\uglify\\index.js:90:11)\n    at done (C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\node_modules\\uglifyjs-webpack-plugin\\dist\\uglify\\index.js:99:22)\n    at C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\node_modules\\uglifyjs-webpack-plugin\\dist\\uglify\\index.js:105:15\n    at C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\node_modules\\worker-farm\\lib\\farm.js:191:19\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"},"message":"Optimizations failure.\n   4395 modules\n    \n    ERROR in ./plugins/sentinl/public/app.js\n    Module build failed: SyntaxError: C:/Developpement/outils/elk/kibana-6.4.0-windows-x86_64/plugins/sentinl/public/app.js: Bad character escape sequence (56:99)\n    \n      54 | import './C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\plugins\\sentinl\\public\\services\\sentinl_helper';\n      55 | import './C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\plugins\\sentinl\\public\\services\\sentinl_log';\n    > 56 | import './C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\plugins\\sentinl\\public\\services\\user_service';\n         |                                                                                                    ^\n      57 | import './C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\plugins\\sentinl\\public\\services\\watcher_service';\n      58 | import './C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\plugins\\sentinl\\public\\constants\\api.js';\n      59 | import './C:\\Developpement\\outils\\elk\\kibana-6.4.0-windows-x86_64\\plugins\\sentinl\\public\\constants\\common.js';\n    \n"}
```

**Comment by havlan** [comment]
@fbaligand  Does it not complete at all? I was able to install the new plugin.
Check https://github.com/havlan/docker-elk/tree/sentinl-6-4-0 to test it again.

**Comment by fbaligand** [comment]
When I go up on the error stack, I see that the root cause error is : 
```

    ERROR in ./plugins/sentinl/public/app.js
    Module build failed: SyntaxError: C:/Developpement/outils/elk/kibana-6.4.0-windows-x86_64/plugins/sentinl/public/app.js: Bad character escape sequence (56:99)

      54 | import './C:\Developpement\outils\elk\kibana-6.4.0-windows-x86_64\plugins\sentinl\public\services\sentinl_helper';
      55 | import './C:\Developpement\outils\elk\kibana-6.4.0-windows-x86_64\plugins\sentinl\public\services\sentinl_log';
    > 56 | import './C:\Developpement\outils\elk\kibana-6.4.0-windows-x86_64\plugins\sentinl\public\services\user_service';
         |                                                                                                    ^
      57 | import './C:\Developpement\outils\elk\kibana-6.4.0-windows-x86_64\plugins\sentinl\public\services\watcher_service';
      58 | import './C:\Developpement\outils\elk\kibana-6.4.0-windows-x86_64\plugins\sentinl\public\constants\api.js';
      59 | import './C:\Developpement\outils\elk\kibana-6.4.0-windows-x86_64\plugins\sentinl\public\constants\common.js';
```

That said, despite this "FATAL" error, oddly, I managed to start Kibana with Sentinl...

Anyway, this is up to me a blocking bug.

**Comment by fbaligand** [comment]
Ok, thanks for the info!

**Comment by sergibondarenko** [comment]
@fbaligand I fixed this. Get the updated package from a release you need. https://github.com/sirensolutions/sentinl/releases

Please reopen this issue if you have any related problem.

**Comment by fbaligand** [comment]
Hi @sergibondarenko 

Thanks for the fix ! 
I just tested it, it works fine !
