### ISSUE TITLE
Unable to start Sentinl page, will get msg=SESSION_EXPIRED

### ISSUE THREAD

**Issue by yudsx0915** [sirensolutions/sentinl#580]
**Kibana version:6.4.2

**Elasticsearch version:6.4.2
Use basic authentication with Nginx for securing the ES and Kibana.

**Server OS version:Red Hat Enterprise Linux 2.6

**Browser version:chrome 69.0.3497.100

**Browser OS version:win 10

**Original install method (e.g. release pkg link, gulp, from source, etc.):**
kibana-plugin install file: sentinl-v6.4.2.zip
**Describe the bug:**
I can't get into the Sentinl page. After starting the Kibana and finishing my username and password,
when I press the Sentinl on the left side, I keep getting SESSION_EXPIRED message.
The url will turn like this:
 http://localhost:5601/logout?next=%2Fapp%2Fsentinl%23%3F_g%3D()&msg=SESSION_EXPIRED

then back to the Kibana home.

**Steps to reproduce:**

**Expected behavior:**

**Sample of data you have in Elasticsearch**

**Full watcher document**

**Screenshots (if relevant):**

**Errors in browser console (if relevant):**

**Provide Kibana logs and/or server output (if relevant):**
Got Error: Unauthorized like below:

>   log   [03:21:05.487] [debug][legacy-platform-proxifier] Request will be handled by proxy GET:/api/security/v1/logout?next=%2Fapp%2Fsentinl%23%3F_g%3D()&msg=SESSION_EXPIRED.
>  error  [03:21:05.499] [debug][auth][security][session] Error: Unauthorized
>     at validate (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\hapi-auth-cookie\lib\index.js:145:49)
>     at Object.authenticate (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\hapi-auth-cookie\lib\index.js:210:13)
>     at module.exports.internals.Auth.internals.Auth.test (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\hapi\lib\auth.js:96:22)
>     at Object.test (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\hapi\lib\plugin.js:65:64)
>     at resolve (D:/ELK/kibana-6.4.2-windows-x86_64/node_modules/x-pack/plugins/security/server/lib/authentication/session.js:56:25)
>     at new Promise (<anonymous>)
>     at Session.get (D:/ELK/kibana-6.4.2-windows-x86_64/node_modules/x-pack/plugins/security/server/lib/authentication/session.js:55:12)
>     at Authenticator._getSessionValue (D:/ELK/kibana-6.4.2-windows-x86_64/node_modules/x-pack/plugins/security/server/lib/authentication/authenticator.js:258:44)
>     at Authenticator.deauthenticate (D:/ELK/kibana-6.4.2-windows-x86_64/node_modules/x-pack/plugins/security/server/lib/authentication/authenticator.js:192:37)
>     at Object.server.expose.request [as deauthenticate] (D:/ELK/kibana-6.4.2-windows-x86_64/node_modules/x-pack/plugins/security/server/lib/authentication/authenticator.js:278:62)
>     at handler (D:/ELK/kibana-6.4.2-windows-x86_64/node_modules/x-pack/plugins/security/server/routes/api/v1/authenticate.js:127:70)
>     at Object.internals.handler (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\hapi\lib\handler.js:96:36)
>     at request._protect.run (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\hapi\lib\handler.js:30:23)
>     at module.exports.internals.Protect.internals.Protect.run (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\hapi\lib\protect.js:64:5)
>     at exports.execute (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\hapi\lib\handler.js:24:22)
>     at each (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\hapi\lib\request.js:384:16)
>     at iterate (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\items\lib\index.js:36:13)
>     at done (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\items\lib\index.js:28:25)
>     at Hoek.once (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\hapi\lib\protect.js:52:16)
>     at wrapped (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\hoek\lib\index.js:879:20)
>     at done (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\items\lib\index.js:31:25)
>     at Function.wrapped [as _next] (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\hoek\lib\index.js:879:20)
>     at Function.internals.continue (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\hapi\lib\reply.js:108:10)
>     at method (D:/ELK/kibana-6.4.2-windows-x86_64/node_modules/x-pack/plugins/dashboard_mode/server/dashboard_mode_request_interceptor.js:44:7)
>     at Items.serial (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\hapi\lib\request.js:403:22)
>     at iterate (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\items\lib\index.js:36:13)
>     at done (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\items\lib\index.js:28:25)
>     at Function.wrapped [as _next] (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\hoek\lib\index.js:879:20)
>     at Function.internals.continue (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\hapi\lib\reply.js:108:10)
>     at D:\ELK\kibana-6.4.2-windows-x86_64\src\server\http\xsrf.js:33:26
>     at Items.serial (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\hapi\lib\request.js:403:22)
>     at iterate (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\items\lib\index.js:36:13)
>     at done (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\items\lib\index.js:28:25)
>     at Function.wrapped [as _next] (D:\ELK\kibana-6.4.2-windows-x86_64\node_modules\hoek\lib\index.js:879:20)
> respons [03:21:05.499]  GET /api/security/v1/logout?next=%2Fapp%2Fsentinl%23%3F_g%3D()&msg=SESSION_EXPIRED 302 3ms - 9.0B

**Any additional context:**
Here is my kibana.yml:
elasticsearch.url: "http://172.xx.xx.xx:xxxx"
elasticsearch.username: "elasticsearch"
elasticsearch.password: "password"
logging.verbose: true
sentinl:
  es:
   host: '172.xx.xx.xx'
   port: xxxx
   protocol: 'http'
  settings:
    authentication:
        enabled: true 
        username: 'elasticsearch'
        password: 'password'
    email:
      active: true
      host: XFMAIL02.pcdc.com.tw
      ssl: false
    report:
      active: true

Thank you for your help, please tell me if I do anything wrong.

**Tips:**

1. Try to query Elasticsearch manually first. Do you receive the results you want for your query?
For example, on Linux, you can query Elasticsearch using `curl`:
```
curl -X GET "localhost:9200/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "query": { 
    "match_all": {}
  }
}
'
```

**Comment by sergibondarenko** [comment]
What do the Nginx logs say?

**Comment by sergibondarenko** [comment]
Also, I would like to recommend you to follow these threads and check if you Nginx config is correct
https://pawelurbanek.com/elk-nginx-logs-setup
https://discuss.elastic.co/t/reverse-proxy-kibana/43647/13
https://discuss.elastic.co/t/reverse-proxy-with-nginx/80244
https://discuss.elastic.co/t/kibana-5-4-behind-nginx/98114/7

**Comment by senlin0820** [comment]
I also encountered the same problem, have you solved it?

**Comment by yudsx0915** [comment]
> 
> 
> I also encountered the same problem, have you solved it?

I got this issue because I put Nginx between the Kibana and Elasticsearch
I solved this problem by changing the ELK version from "standard" to "OSS"
and moving Nginx outside, the before and after like below:
Before:
"Browser"-->"Kibana"-->"Nginx"-->"Elasticsearch"

After:
"Browser"-->"Nginx"-->"Kibana"-->"Elasticsearch"
