### ISSUE TITLE
SENTINL with ReadonlyREST authentication

### ISSUE THREAD

**Issue by Tvlasev** [sirensolutions/sentinl#667]
| Type         | Version |
|--------------|---------|
| Kibana       |  6.5.4        |
| Elasticsearc | 6.5.4        |
| Server OS    |    Windows 10     |
| Browser      |    Chrome     |

I've installed sentiln plugin 6.5.4 version in kibana and I've added these options from the faq section in readonlyrest.yml file: 

```
    - name: ALLOWPOST
      type: allow
      methods: [POST,HEAD,GET,DELETE,OPTIONS]
      uri_re:  ^/watcher_alarms-.*/
      hosts: [localhost]
      verbosity: info

    - name: ALLOWHEAD
      type: allow
      methods: [POST,HEAD,GET,DELETE]
      uri_re:  ^/watcher.*/
      hosts: [localhost]
      verbosity: info
```

In kibana.yml file I've added this: 

```
sentinl:
  settings:
    authentication:
      enabled: true 
      username: '<username>'
      password: '<password>'
```

But In kibana I still have an error: 

Watchers: list watchers : list watcher : [undefined] Sorry, your request is forbidden!

Error: list watchers : list watcher : [undefined] Sorry, your request is forbidden!

Error: list watcher : [undefined] Sorry, your request is forbidden!
    at new SentinlError (http://localhost:5601/bundles/sentinl.bundle.js:48:241173)
    at WatcherService._callee4$ (http://localhost:5601/bundles/sentinl.bundle.js:48:262600)
    at tryCatch (http://localhost:5601/bundles/vendors.bundle.js:42:274213)
    at Generator.invoke [as _invoke] (http://localhost:5601/bundles/vendors.bundle.js:42:278095)
    at Generator.prototype.(anonymous function) [as throw] (http://localhost:5601/bundles/vendors.bundle.js:42:275336)
    at step (http://localhost:5601/bundles/sentinl.bundle.js:48:259126)
    at http://localhost:5601/bundles/sentinl.bundle.js:48:259286

"Sorry, your request is forbidden!" is comming from readonlyrest.yml  file option: response_if_req_forbidden: "Sorry, your request is forbidden!"

**Comment by Tvlasev** [comment]
Thank you for the help
