### ISSUE TITLE
Support for Handlebar.js

### ISSUE THREAD

**Issue by sethyes** [sirensolutions/sentinl#696]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |   6.4.2      |
| Elasticsearc |    6.4.2     |
| Server OS    |    Ubuntu 16.04     |
| Browser      |     Chrome 72.0.3626.119     |

#### Original Install Method

- [X ] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: 

#### Steps to Reproduce
1. Create an Elasticsearch query which returns multiple buckets (.e.g. metrics for 3 keys which you want to alert on)
2. Push that query into an advanced watcher with the intent to alert on any single value being below a threshold
3. Get discouraged when you realize you need to create an alert for each metric, rather than comparing *any* metric to the threshold

#### Sample of data you have in Elasticsearch
```
{
  "took": 17,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 8640,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "2": {
      "buckets": [
        {
          "1": {
            "value": 25.4
          },
          "3": {
            "value": 24
          },
          "4": {
            "value": 25
          },
          "5": {
            "value": 25
          },
          "6": {
            "value": 23.32
          }
        }
      ]
    }
  }
}
```

#### Full Watcher JSON
```
{
  "actions": {
    "email_html_alarm_69546495-4344-45e1-8cb5-a9dd5cc34b21": {
      "name": "email html alarm",
      "throttle_period": "1m",
      "email_html": {
        "stateless": false,
        "subject": "{{payload.hits.total}} new results from watcher {{watcher.title}}",
        "priority": "high",
        "html": "<p>Hi {{watcher.username}}</p>\n<p>There are {{payload.hits.total}} results found by the watcher <i>{{watcher.title}}</i>.</p>\n\n<div style=\"color:grey;\">\n  <hr />\n  <p>This watcher sends alerts based on the following criteria:</p>\n  <ul><li>{{watcher.wizard.chart_query_params.queryType}} of {{watcher.wizard.chart_query_params.over.type}} over the last {{watcher.wizard.chart_query_params.last.n}} {{watcher.wizard.chart_query_params.last.unit}} {{watcher.wizard.chart_query_params.threshold.direction}} {{watcher.wizard.chart_query_params.threshold.n}} in index {{watcher.wizard.chart_query_params.index}}</li></ul>\n</div>",
        "from": "test-sender@test.com",
        "to": "test-receiver@test.com"
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "bmc-*"
        ],
        "body": {
          "query": {
            "bool": {
              "filter": {
                "range": {
                  "@timestamp": {
                    "gte": "now-5m/m",
                    "lte": "now/m",
                    "format": "epoch_millis"
                  }
                }
              }
            }
          },
          "size": 0,
          "aggs": {
            "dateAgg": {
              "date_histogram": {
                "field": "@timestamp",
                "time_zone": "American/Denver",
                "interval": "1m",
                "min_doc_count": 1
              },
              "aggs": {
                "metricAgg": {
                  "1": {
                    "avg": {
                      "field": "beckhoff_fan_current_1_1"
                    }
                  },
                  "3": {
                    "avg": {
                      "field": "beckhoff_fan_current_1_2"
                    }
                  },
                  "4": {
                    "avg": {
                      "field": "beckhoff_fan_current_2_1"
                    }
                  },
                  "5": {
                    "avg": {
                      "field": "beckhoff_fan_current_2_2"
                    }
                  },
                  "6": {
                    "avg": {
                      "field": "beckhoff_fan_current_3_1"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": {
      "script": "{{#payload.aggregations.dateAgg.buckets}}{{#each .}}{{value}} < 24{{/each}}{{/payload.aggregations.dateAgg.buckets}}"
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 2 minutes"
    }
  },
  "disable": false,
  "report": false,
  "title": "Beckhoff Fan Current",
  "wizard": {},
  "save_payload": false,
  "spy": false,
  "impersonate": false
}
```

#### Errors in Browser Console (if relevant)
```
Error: Execute watcher:Execute 'watcher'
Error: Execute 'watcher'
    at new SentinlError (http://my-test-server/bundles/sentinl.bundle.js:3:92075)
    at WatcherService._callee$ (http://my-test-server/bundles/sentinl.bundle.js:25:352531)
    at tryCatch (http://my-test-server/bundles/vendors.bundle.js:50:580793)
    at Generator.invoke [as _invoke] (http://my-test-server/bundles/vendors.bundle.js:50:584675)
    at Generator.prototype.(anonymous function) [as throw] (http://my-test-server/bundles/vendors.bundle.js:50:581916)
    at step (http://my-test-server/bundles/sentinl.bundle.js:25:351051)
    at http://my-test-server/bundles/sentinl.bundle.js:25:351211
```

#### Kibana logs and/or server output (attached if relevant)
```
{"type":"log","@timestamp":"2019-03-07T23:08:00Z","tags":["error","Sentinl","scheduler"],"pid":2791,"message":"watcher a58b4150-3fb8-11e9-b4f7-a34019239f3d: schedule execute: WatcherWizardHandlerError: execute wizard watcher:exec search:search:[named_object_not_found_exception] [1:268] unable to parse BaseAggregationBuilder with name [1]: parser not found: [named_object_not_found_exception] [1:268] unable to parse BaseAggregationBuilder with name [1]: parser not found :: {\"path\":\"/my-test-index-*/_search\",\"query\":{},\"body\":\"{\\\"query\\\":{\\\"bool\\\":{\\\"filter\\\":{\\\"range\\\":{\\\"@timestamp\\\":{\\\"gte\\\":\\\"now-5m/m\\\",\\\"lte\\\":\\\"now/m\\\",\\\"format\\\":\\\"epoch_millis\\\"}}}}},\\\"size\\\":0,\\\"aggs\\\":{\\\"dateAgg\\\":{\\\"date_histogram\\\":{\\\"field\\\":\\\"@timestamp\\\",\\\"time_zone\\\":\\\"America/Denver\\\",\\\"interval\\\":\\\"1m\\\",\\\"min_doc_count\\\":1},\\\"aggs\\\":{\\\"metricAgg\\\":{\\\"1\\\":{\\\"avg\\\":{\\\"field\\\":\\\"beckhoff_fan_current_1_1\\\"}},\\\"3\\\":{\\\"avg\\\":{\\\"field\\\":\\\"beckhoff_fan_current_1_2\\\"}},\\\"4\\\":{\\\"avg\\\":{\\\"field\\\":\\\"beckhoff_fan_current_2_1\\\"}},\\\"5\\\":{\\\"avg\\\":{\\\"field\\\":\\\"beckhoff_fan_current_2_2\\\"}},\\\"6\\\":{\\\"avg\\\":{\\\"field\\\":\\\"beckhoff_fan_current_3_1\\\"}}}}}}}\",\"statusCode\":400,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"named_object_not_found_exception\\\",\\\"reason\\\":\\\"[1:268] unable to parse BaseAggregationBuilder with name [1]: parser not found\\\"}],\\\"type\\\":\\\"named_object_not_found_exception\\\",\\\"reason\\\":\\\"[1:268] unable to parse BaseAggregationBuilder with name [1]: parser not found\\\"},\\\"status\\\":400}\"}\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:307:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:266:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)\n    at IncomingMessage.bound (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)"}
```
#### Any additional information
This would work if we had handlebar.js, however mustache does not support iterating over values in a bucket such as this. If it does, I haven't found the correct syntax. The current workaround would be for me to create an alert for each of these individual buckets, which is hard to difficult to setup and maintain.

**Comment by lmangani** [comment]
Manual mode is manual and the beauty is the freedom to be complex. The wizard in the latest versions should address this by providing easy access for the same condition. Is this something you've already tried or considered?

**Comment by sethyes** [comment]
I'll give it a shot. Thanks
