### ISSUE TITLE
problem after installing sentinl kibana ver 6.3.1

### ISSUE THREAD

**Issue by lelgazar** [sirensolutions/sentinl#767]
<!--hi i'm using kibana ver 6.3.1, i have installed the sentinl plugin but when i'm trying to enable some of feautures of sentinl in the kibana.yml i get the following error

(node:26048) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead. error [09:26:11.414] [fatal] Error: Option "sentinl.sentinl.results" was deprecated. Use "sentinl.es.results" instead! at appConfig (/usr/share/kibana/plugins/sentinl/app_config.js:5:42) at config (/usr/share/kibana/plugins/sentinl/index.js:45:14) at getSchema (/usr/share/kibana/src/plugin_discovery/plugin_config/schema.js:30:29) at extendConfigService (/usr/share/kibana/src/plugin_discovery/plugin_config/extend_config_service.js:25:46) at <anonymous> FATAL Error: Option "sentinl.sentinl.results" was deprecated. Use "sentinl.es.results" instead! at appConfig (/usr/share/kibana/plugins/sentinl/app_config.js:5:42) at config (/usr/share/kibana/plugins/sentinl/index.js:45:14) at getSchema (/usr/share/kibana/src/plugin_discovery/plugin_config/schema.js:30:29) at extendConfigService (/usr/share/kibana/src/plugin_discovery/plugin_config/extend_config_service.js:25:46) at <anonymous>
please help

**Comment by lelgazar** [comment]
new relevant opened
