### ISSUE TITLE
Not able to configure email sending without authentication

### ISSUE THREAD

**Issue by shamil** [sirensolutions/sentinl#86]
Since config moved to `kibana.yml` I can't specify empty `username/password` for email. My SMTP local relay doesn't require authentication. Is that something that is known limitation?

Now I require to pass username/password in the configuration. Before I was able to specify `username/password` as `null`  in `sentinl.json` and `email.js` knew that no authentication required.

Currently I'm not able to send emails!

Here is a relevant log from kibana:

```
{"type":"log","@timestamp":"2016-12-27T12:20:00Z","tags":["status","info","Sentinl","email"],"pid":11,"level":"error","message":"no form of authorization supported","error":{"message":"no form of authorization supported","name":"Error","stack":"Error: no form of authorization supported
    at module.exports (/opt/kibana/installedPlugins/sentinl/node_modules/emailjs/smtp/error.js:3:13)
    at initiate (/opt/kibana/installedPlugins/sentinl/node_modules/emailjs/smtp/smtp.js:536:44)
    at caller (/opt/kibana/installedPlugins/sentinl/node_modules/emailjs/smtp/smtp.js:48:14)
    at attempt (/opt/kibana/installedPlugins/sentinl/node_modules/emailjs/smtp/smtp.js:415:14)
    at caller (/opt/kibana/installedPlugins/sentinl/node_modules/emailjs/smtp/smtp.js:48:14)
    at response (/opt/kibana/installedPlugins/sentinl/node_modules/emailjs/smtp/smtp.js:345:13)
    at caller (/opt/kibana/installedPlugins/sentinl/node_modules/emailjs/smtp/smtp.js:48:14)
    at response (/opt/kibana/installedPlugins/sentinl/node_modules/emailjs/smtp/smtp.js:201:11)
    at caller (/opt/kibana/installedPlugins/sentinl/node_modules/emailjs/smtp/smtp.js:48:14)
    at Socket.response (/opt/kibana/installedPlugins/sentinl/node_modules/emailjs/smtp/smtp.js:181:11)
    at Socket.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at Socket.emit (events.js:172:7)
    at notify (/opt/kibana/installedPlugins/sentinl/node_modules/emailjs/smtp/response.js:19:14)
    at Socket.watch (/opt/kibana/installedPlugins/sentinl/node_modules/emailjs/smtp/response.js:44:7)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)","code":7}}
```

**Comment by lmangani** [comment]
Could you confirm if your email action used to work with the old configuration and the same settings?

**Comment by shamil** [comment]
@lmangani, yes it was working. I was specifing `null` in `user/password`

      "email" : {
         "user": null,
         "password": null,
         "host": "localhost",
         "ssl": false,
         "active": true
       }

**Comment by lmangani** [comment]
what if you skip the user and password parameters altogether in yaml?

**Comment by shamil** [comment]
@lmangani works! I was under impression that those are mandatory, at least in the old configuration.
Thanks for your help. Closing...

**Comment by lmangani** [comment]
Thanks for the update! Glad its working as intended ;)
